//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use super::*;
pub const CLAIM_REWARD_IX_ACCOUNTS_LEN: usize = 11;
///Accounts struct for the claimReward instruction
#[derive(Copy, Clone, Debug)]
pub struct ClaimRewardAccounts<'me, 'info> {
    pub lb_pair: &'me AccountInfo<'info>,
    pub position: &'me AccountInfo<'info>,
    pub bin_array_lower: &'me AccountInfo<'info>,
    pub bin_array_upper: &'me AccountInfo<'info>,
    pub sender: &'me AccountInfo<'info>,
    pub reward_vault: &'me AccountInfo<'info>,
    pub reward_mint: &'me AccountInfo<'info>,
    pub user_token_account: &'me AccountInfo<'info>,
    pub token_program: &'me AccountInfo<'info>,
    pub event_authority: &'me AccountInfo<'info>,
    pub program: &'me AccountInfo<'info>,
}
///Public keys struct for the claimReward instruction
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct ClaimRewardKeys {
    pub lb_pair: Pubkey,
    pub position: Pubkey,
    pub bin_array_lower: Pubkey,
    pub bin_array_upper: Pubkey,
    pub sender: Pubkey,
    pub reward_vault: Pubkey,
    pub reward_mint: Pubkey,
    pub user_token_account: Pubkey,
    pub token_program: Pubkey,
    pub event_authority: Pubkey,
    pub program: Pubkey,
}
impl From<ClaimRewardAccounts<'_, '_>> for ClaimRewardKeys {
    fn from(accounts: ClaimRewardAccounts) -> Self {
        Self {
            lb_pair: *accounts.lb_pair.key,
            position: *accounts.position.key,
            bin_array_lower: *accounts.bin_array_lower.key,
            bin_array_upper: *accounts.bin_array_upper.key,
            sender: *accounts.sender.key,
            reward_vault: *accounts.reward_vault.key,
            reward_mint: *accounts.reward_mint.key,
            user_token_account: *accounts.user_token_account.key,
            token_program: *accounts.token_program.key,
            event_authority: *accounts.event_authority.key,
            program: *accounts.program.key,
        }
    }
}
impl From<ClaimRewardKeys> for [AccountMeta; CLAIM_REWARD_IX_ACCOUNTS_LEN] {
    fn from(keys: ClaimRewardKeys) -> Self {
        [
            AccountMeta {
                pubkey: keys.lb_pair,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.position,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.bin_array_lower,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.bin_array_upper,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.sender,
                is_signer: true,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.reward_vault,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.reward_mint,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.user_token_account,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.token_program,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.event_authority,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.program,
                is_signer: false,
                is_writable: false,
            },
        ]
    }
}
impl From<[Pubkey; CLAIM_REWARD_IX_ACCOUNTS_LEN]> for ClaimRewardKeys {
    fn from(pubkeys: [Pubkey; CLAIM_REWARD_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            lb_pair: pubkeys[0],
            position: pubkeys[1],
            bin_array_lower: pubkeys[2],
            bin_array_upper: pubkeys[3],
            sender: pubkeys[4],
            reward_vault: pubkeys[5],
            reward_mint: pubkeys[6],
            user_token_account: pubkeys[7],
            token_program: pubkeys[8],
            event_authority: pubkeys[9],
            program: pubkeys[10],
        }
    }
}
impl From<&[String]> for ClaimRewardKeys {
    fn from(pubkeys: &[String]) -> Self {
        Self {
            lb_pair: pubkeys[0].parse().unwrap(),
            position: pubkeys[1].parse().unwrap(),
            bin_array_lower: pubkeys[2].parse().unwrap(),
            bin_array_upper: pubkeys[3].parse().unwrap(),
            sender: pubkeys[4].parse().unwrap(),
            reward_vault: pubkeys[5].parse().unwrap(),
            reward_mint: pubkeys[6].parse().unwrap(),
            user_token_account: pubkeys[7].parse().unwrap(),
            token_program: pubkeys[8].parse().unwrap(),
            event_authority: pubkeys[9].parse().unwrap(),
            program: pubkeys[10].parse().unwrap(),
        }
    }
}
impl<'info> From<ClaimRewardAccounts<'_, 'info>>
    for [AccountInfo<'info>; CLAIM_REWARD_IX_ACCOUNTS_LEN]
{
    fn from(accounts: ClaimRewardAccounts<'_, 'info>) -> Self {
        [
            accounts.lb_pair.clone(),
            accounts.position.clone(),
            accounts.bin_array_lower.clone(),
            accounts.bin_array_upper.clone(),
            accounts.sender.clone(),
            accounts.reward_vault.clone(),
            accounts.reward_mint.clone(),
            accounts.user_token_account.clone(),
            accounts.token_program.clone(),
            accounts.event_authority.clone(),
            accounts.program.clone(),
        ]
    }
}
impl<'me, 'info> From<&'me [AccountInfo<'info>; CLAIM_REWARD_IX_ACCOUNTS_LEN]>
    for ClaimRewardAccounts<'me, 'info>
{
    fn from(arr: &'me [AccountInfo<'info>; CLAIM_REWARD_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            lb_pair: &arr[0],
            position: &arr[1],
            bin_array_lower: &arr[2],
            bin_array_upper: &arr[3],
            sender: &arr[4],
            reward_vault: &arr[5],
            reward_mint: &arr[6],
            user_token_account: &arr[7],
            token_program: &arr[8],
            event_authority: &arr[9],
            program: &arr[10],
        }
    }
}
pub const CLAIM_REWARD_IX_DISCM: u8 = 23u8;
///Arguments for the claimReward instruction
#[derive(BorshDeserialize, BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClaimRewardIxArgs {
    pub discriminator: u8,
    pub reward_index: u64,
}
impl Default for ClaimRewardIxArgs {
    fn default() -> Self {
        Self {
            discriminator: 23u8,
            reward_index: Default::default(),
        }
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct ClaimRewardIxData(pub ClaimRewardIxArgs);
impl From<ClaimRewardIxArgs> for ClaimRewardIxData {
    fn from(args: ClaimRewardIxArgs) -> Self {
        Self(args)
    }
}
impl ClaimRewardIxData {
    pub fn deserialize(buf: &[u8]) -> std::io::Result<Self> {
        if buf.is_empty() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Instruction data is empty",
            ));
        }
        let maybe_discm = buf[0];
        if maybe_discm != CLAIM_REWARD_IX_DISCM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "discm does not match. Expected: {}. Received: {}",
                    CLAIM_REWARD_IX_DISCM, maybe_discm
                ),
            ));
        }
        let mut reader = &buf[1..];
        Ok(Self(ClaimRewardIxArgs::deserialize(&mut reader)?))
    }
    pub fn serialize<W: std::io::Write>(&self, mut writer: W) -> std::io::Result<()> {
        writer.write_all(&[CLAIM_REWARD_IX_DISCM])?;
        self.0.serialize(&mut writer)
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        let mut data = Vec::new();
        self.serialize(&mut data)?;
        Ok(data)
    }
}
pub fn claim_reward_ix_with_program_id(
    program_id: Pubkey,
    keys: ClaimRewardKeys,
    args: ClaimRewardIxArgs,
) -> std::io::Result<Instruction> {
    let metas: [AccountMeta; CLAIM_REWARD_IX_ACCOUNTS_LEN] = keys.into();
    let data: ClaimRewardIxData = args.into();
    Ok(Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: data.try_to_vec()?,
    })
}
pub fn claim_reward_ix(
    keys: ClaimRewardKeys,
    args: ClaimRewardIxArgs,
) -> std::io::Result<Instruction> {
    claim_reward_ix_with_program_id(crate::ID, keys, args)
}
pub fn claim_reward_invoke_with_program_id(
    program_id: Pubkey,
    accounts: ClaimRewardAccounts<'_, '_>,
    args: ClaimRewardIxArgs,
) -> ProgramResult {
    let keys: ClaimRewardKeys = accounts.into();
    let ix = claim_reward_ix_with_program_id(program_id, keys, args)?;
    invoke_instruction(&ix, accounts)
}
pub fn claim_reward_invoke(
    accounts: ClaimRewardAccounts<'_, '_>,
    args: ClaimRewardIxArgs,
) -> ProgramResult {
    claim_reward_invoke_with_program_id(crate::ID, accounts, args)
}
pub fn claim_reward_invoke_signed_with_program_id(
    program_id: Pubkey,
    accounts: ClaimRewardAccounts<'_, '_>,
    args: ClaimRewardIxArgs,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    let keys: ClaimRewardKeys = accounts.into();
    let ix = claim_reward_ix_with_program_id(program_id, keys, args)?;
    invoke_instruction_signed(&ix, accounts, seeds)
}
pub fn claim_reward_invoke_signed(
    accounts: ClaimRewardAccounts<'_, '_>,
    args: ClaimRewardIxArgs,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    claim_reward_invoke_signed_with_program_id(crate::ID, accounts, args, seeds)
}
pub fn claim_reward_verify_account_keys(
    accounts: ClaimRewardAccounts<'_, '_>,
    keys: ClaimRewardKeys,
) -> Result<(), (Pubkey, Pubkey)> {
    for (actual, expected) in [
        (*accounts.lb_pair.key, keys.lb_pair),
        (*accounts.position.key, keys.position),
        (*accounts.bin_array_lower.key, keys.bin_array_lower),
        (*accounts.bin_array_upper.key, keys.bin_array_upper),
        (*accounts.sender.key, keys.sender),
        (*accounts.reward_vault.key, keys.reward_vault),
        (*accounts.reward_mint.key, keys.reward_mint),
        (*accounts.user_token_account.key, keys.user_token_account),
        (*accounts.token_program.key, keys.token_program),
        (*accounts.event_authority.key, keys.event_authority),
        (*accounts.program.key, keys.program),
    ] {
        if actual != expected {
            return Err((actual, expected));
        }
    }
    Ok(())
}
impl ClaimRewardIxArgs {
    pub fn serialize<W: std::io::Write>(&self, mut writer: W) -> std::io::Result<()> {
        BorshSerialize::serialize(self, &mut writer)
    }
    pub fn deserialize(buf: &[u8]) -> std::io::Result<Self> {
        BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
}
impl From<ClaimRewardIxArgs> for MeteoraDlmmProgramIx {
    fn from(args: ClaimRewardIxArgs) -> Self {
        Self::ClaimReward(args)
    }
}
