//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use borsh::{BorshDeserialize, BorshSerialize};
use solana_program::pubkey::Pubkey;
///Metadata for a virtual pool.
#[derive(Clone, Debug, BorshDeserialize, BorshSerialize, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct VirtualPoolMetadata {
    ///virtual pool
    pub virtual_pool: Pubkey,
    ///padding for future use
    pub padding: [u128; 6],
    ///Name of project.
    pub name: String,
    ///Website of project.
    pub website: String,
    ///Logo of project
    pub logo: String,
}
impl Default for VirtualPoolMetadata {
    fn default() -> Self {
        Self {
            virtual_pool: Default::default(),
            padding: core::array::from_fn(|_| Default::default()),
            name: Default::default(),
            website: Default::default(),
            logo: Default::default(),
        }
    }
}
