//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-15
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!Instruction: collectFeesV2
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const COLLECT_FEES_V_2_IX_DISCM: [u8; 8] =
    [144u8, 29u8, 26u8, 226u8, 250u8, 71u8, 253u8, 203u8];
pub const COLLECT_FEES_V_2_IX_ACCOUNTS_LEN: usize = 13;
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CollectFeesV2IxData {
    pub discriminator: [u8; 8],
    #[cfg_attr(feature = "serde", serde(rename = "remainingAccountsInfo"))]
    pub remaining_accounts_info: Option<crate::types::RemainingAccountsInfo>,
}
impl Default for CollectFeesV2IxData {
    fn default() -> Self {
        Self {
            discriminator: COLLECT_FEES_V_2_IX_DISCM,
            remaining_accounts_info: Default::default(),
        }
    }
}
impl CollectFeesV2IxData {
    pub fn new(remaining_accounts_info: Option<crate::types::RemainingAccountsInfo>) -> Self {
        Self {
            discriminator: Self::discriminator(),
            remaining_accounts_info,
        }
    }
    pub fn from_bytes(buf: &[u8]) -> std::io::Result<Self> {
        borsh::BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn discriminator() -> [u8; 8] {
        COLLECT_FEES_V_2_IX_DISCM
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!(
                    "\"discriminator\":[{}]",
                    self.discriminator
                        .iter()
                        .map(|x| x.to_string())
                        .collect::<Vec<_>>()
                        .join(",")
                ),
                format!(
                    "\"{}\":{}",
                    "remaining_accounts_info",
                    serde_json::to_string(&self.remaining_accounts_info)
                        .unwrap_or_else(|_| "null".to_string())
                )
            ]
            .join(",")
        )
    }
}
#[derive(Copy, Clone, Debug, PartialEq, Default)]
pub struct CollectFeesV2Keys {
    pub whirlpool: Pubkey,
    pub position_authority: Pubkey,
    pub position: Pubkey,
    pub position_token_account: Pubkey,
    pub token_mint_a: Pubkey,
    pub token_mint_b: Pubkey,
    pub token_owner_account_a: Pubkey,
    pub token_vault_a: Pubkey,
    pub token_owner_account_b: Pubkey,
    pub token_vault_b: Pubkey,
    pub token_program_a: Pubkey,
    pub token_program_b: Pubkey,
    pub memo_program: Pubkey,
}
impl From<&[Pubkey]> for CollectFeesV2Keys {
    fn from(pubkeys: &[Pubkey]) -> Self {
        Self {
            whirlpool: pubkeys[0],
            position_authority: pubkeys[1],
            position: pubkeys[2],
            position_token_account: pubkeys[3],
            token_mint_a: pubkeys[4],
            token_mint_b: pubkeys[5],
            token_owner_account_a: pubkeys[6],
            token_vault_a: pubkeys[7],
            token_owner_account_b: pubkeys[8],
            token_vault_b: pubkeys[9],
            token_program_a: pubkeys[10],
            token_program_b: pubkeys[11],
            memo_program: pubkeys[12],
        }
    }
}
impl CollectFeesV2Keys {
    /// Convert Keys to Vec<Pubkey>
    pub fn to_vec(&self) -> Vec<Pubkey> {
        vec![
            self.whirlpool,
            self.position_authority,
            self.position,
            self.position_token_account,
            self.token_mint_a,
            self.token_mint_b,
            self.token_owner_account_a,
            self.token_vault_a,
            self.token_owner_account_b,
            self.token_vault_b,
            self.token_program_a,
            self.token_program_b,
            self.memo_program,
        ]
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!("\"{}\":\"{}\"", "whirlpool", self.whirlpool),
                format!(
                    "\"{}\":\"{}\"",
                    "positionAuthority", self.position_authority
                ),
                format!("\"{}\":\"{}\"", "position", self.position),
                format!(
                    "\"{}\":\"{}\"",
                    "positionTokenAccount", self.position_token_account
                ),
                format!("\"{}\":\"{}\"", "tokenMintA", self.token_mint_a),
                format!("\"{}\":\"{}\"", "tokenMintB", self.token_mint_b),
                format!(
                    "\"{}\":\"{}\"",
                    "tokenOwnerAccountA", self.token_owner_account_a
                ),
                format!("\"{}\":\"{}\"", "tokenVaultA", self.token_vault_a),
                format!(
                    "\"{}\":\"{}\"",
                    "tokenOwnerAccountB", self.token_owner_account_b
                ),
                format!("\"{}\":\"{}\"", "tokenVaultB", self.token_vault_b),
                format!("\"{}\":\"{}\"", "tokenProgramA", self.token_program_a),
                format!("\"{}\":\"{}\"", "tokenProgramB", self.token_program_b),
                format!("\"{}\":\"{}\"", "memoProgram", self.memo_program)
            ]
            .join(",")
        )
    }
}
impl From<CollectFeesV2Keys>
    for [solana_instruction::AccountMeta; COLLECT_FEES_V_2_IX_ACCOUNTS_LEN]
{
    fn from(keys: CollectFeesV2Keys) -> Self {
        [
            solana_instruction::AccountMeta::new(keys.whirlpool, false),
            solana_instruction::AccountMeta::new(keys.position_authority, false),
            solana_instruction::AccountMeta::new(keys.position, false),
            solana_instruction::AccountMeta::new(keys.position_token_account, false),
            solana_instruction::AccountMeta::new(keys.token_mint_a, false),
            solana_instruction::AccountMeta::new(keys.token_mint_b, false),
            solana_instruction::AccountMeta::new(keys.token_owner_account_a, false),
            solana_instruction::AccountMeta::new(keys.token_vault_a, false),
            solana_instruction::AccountMeta::new(keys.token_owner_account_b, false),
            solana_instruction::AccountMeta::new(keys.token_vault_b, false),
            solana_instruction::AccountMeta::new(keys.token_program_a, false),
            solana_instruction::AccountMeta::new(keys.token_program_b, false),
            solana_instruction::AccountMeta::new(keys.memo_program, false),
        ]
    }
}
pub fn collect_fees_v_2_ix_with_program_id(
    program_id: Pubkey,
    keys: CollectFeesV2Keys,
    args: CollectFeesV2IxData,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    let metas: [solana_instruction::AccountMeta; COLLECT_FEES_V_2_IX_ACCOUNTS_LEN] = keys.into();
    Ok(solana_instruction::Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: args.try_to_vec()?,
    })
}
pub fn collect_fees_v_2_ix(
    keys: CollectFeesV2Keys,
    args: CollectFeesV2IxData,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    collect_fees_v_2_ix_with_program_id(crate::ID, keys, args)
}
