//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-15
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!Instruction: deletePositionBundle
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const DELETE_POSITION_BUNDLE_IX_DISCM: [u8; 8] =
    [158u8, 224u8, 56u8, 93u8, 107u8, 151u8, 209u8, 141u8];
pub const DELETE_POSITION_BUNDLE_IX_ACCOUNTS_LEN: usize = 6;
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DeletePositionBundleIxData {
    pub discriminator: [u8; 8],
}
impl Default for DeletePositionBundleIxData {
    fn default() -> Self {
        Self {
            discriminator: DELETE_POSITION_BUNDLE_IX_DISCM,
        }
    }
}
impl DeletePositionBundleIxData {
    pub fn new() -> Self {
        Self {
            discriminator: Self::discriminator(),
        }
    }
    pub fn from_bytes(buf: &[u8]) -> std::io::Result<Self> {
        borsh::BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn discriminator() -> [u8; 8] {
        DELETE_POSITION_BUNDLE_IX_DISCM
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [format!(
                "\"discriminator\":[{}]",
                self.discriminator
                    .iter()
                    .map(|x| x.to_string())
                    .collect::<Vec<_>>()
                    .join(",")
            )]
            .join(",")
        )
    }
}
#[derive(Copy, Clone, Debug, PartialEq, Default)]
pub struct DeletePositionBundleKeys {
    pub position_bundle: Pubkey,
    pub position_bundle_mint: Pubkey,
    pub position_bundle_token_account: Pubkey,
    pub position_bundle_owner: Pubkey,
    pub receiver: Pubkey,
    pub token_program: Pubkey,
}
impl From<&[Pubkey]> for DeletePositionBundleKeys {
    fn from(pubkeys: &[Pubkey]) -> Self {
        Self {
            position_bundle: pubkeys[0],
            position_bundle_mint: pubkeys[1],
            position_bundle_token_account: pubkeys[2],
            position_bundle_owner: pubkeys[3],
            receiver: pubkeys[4],
            token_program: pubkeys[5],
        }
    }
}
impl DeletePositionBundleKeys {
    /// Convert Keys to Vec<Pubkey>
    pub fn to_vec(&self) -> Vec<Pubkey> {
        vec![
            self.position_bundle,
            self.position_bundle_mint,
            self.position_bundle_token_account,
            self.position_bundle_owner,
            self.receiver,
            self.token_program,
        ]
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!("\"{}\":\"{}\"", "positionBundle", self.position_bundle),
                format!(
                    "\"{}\":\"{}\"",
                    "positionBundleMint", self.position_bundle_mint
                ),
                format!(
                    "\"{}\":\"{}\"",
                    "positionBundleTokenAccount", self.position_bundle_token_account
                ),
                format!(
                    "\"{}\":\"{}\"",
                    "positionBundleOwner", self.position_bundle_owner
                ),
                format!("\"{}\":\"{}\"", "receiver", self.receiver),
                format!("\"{}\":\"{}\"", "tokenProgram", self.token_program)
            ]
            .join(",")
        )
    }
}
impl From<DeletePositionBundleKeys>
    for [solana_instruction::AccountMeta; DELETE_POSITION_BUNDLE_IX_ACCOUNTS_LEN]
{
    fn from(keys: DeletePositionBundleKeys) -> Self {
        [
            solana_instruction::AccountMeta::new(keys.position_bundle, false),
            solana_instruction::AccountMeta::new(keys.position_bundle_mint, false),
            solana_instruction::AccountMeta::new(keys.position_bundle_token_account, false),
            solana_instruction::AccountMeta::new(keys.position_bundle_owner, false),
            solana_instruction::AccountMeta::new(keys.receiver, false),
            solana_instruction::AccountMeta::new(keys.token_program, false),
        ]
    }
}
pub fn delete_position_bundle_ix_with_program_id(
    program_id: Pubkey,
    keys: DeletePositionBundleKeys,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    let metas: [solana_instruction::AccountMeta; DELETE_POSITION_BUNDLE_IX_ACCOUNTS_LEN] =
        keys.into();
    let args = DeletePositionBundleIxData::default();
    Ok(solana_instruction::Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: args.try_to_vec()?,
    })
}
pub fn delete_position_bundle_ix(
    keys: DeletePositionBundleKeys,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    delete_position_bundle_ix_with_program_id(crate::ID, keys)
}
