//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-15
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!Instruction: setFeeAuthority
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const SET_FEE_AUTHORITY_IX_DISCM: [u8; 8] = [22u8, 26u8, 62u8, 29u8, 184u8, 67u8, 201u8, 240u8];
pub const SET_FEE_AUTHORITY_IX_ACCOUNTS_LEN: usize = 3;
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetFeeAuthorityIxData {
    pub discriminator: [u8; 8],
}
impl Default for SetFeeAuthorityIxData {
    fn default() -> Self {
        Self {
            discriminator: SET_FEE_AUTHORITY_IX_DISCM,
        }
    }
}
impl SetFeeAuthorityIxData {
    pub fn new() -> Self {
        Self {
            discriminator: Self::discriminator(),
        }
    }
    pub fn from_bytes(buf: &[u8]) -> std::io::Result<Self> {
        borsh::BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn discriminator() -> [u8; 8] {
        SET_FEE_AUTHORITY_IX_DISCM
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [format!(
                "\"discriminator\":[{}]",
                self.discriminator
                    .iter()
                    .map(|x| x.to_string())
                    .collect::<Vec<_>>()
                    .join(",")
            )]
            .join(",")
        )
    }
}
#[derive(Copy, Clone, Debug, PartialEq, Default)]
pub struct SetFeeAuthorityKeys {
    pub whirlpools_config: Pubkey,
    pub fee_authority: Pubkey,
    pub new_fee_authority: Pubkey,
}
impl From<&[Pubkey]> for SetFeeAuthorityKeys {
    fn from(pubkeys: &[Pubkey]) -> Self {
        Self {
            whirlpools_config: pubkeys[0],
            fee_authority: pubkeys[1],
            new_fee_authority: pubkeys[2],
        }
    }
}
impl SetFeeAuthorityKeys {
    /// Convert Keys to Vec<Pubkey>
    pub fn to_vec(&self) -> Vec<Pubkey> {
        vec![
            self.whirlpools_config,
            self.fee_authority,
            self.new_fee_authority,
        ]
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!("\"{}\":\"{}\"", "whirlpoolsConfig", self.whirlpools_config),
                format!("\"{}\":\"{}\"", "feeAuthority", self.fee_authority),
                format!("\"{}\":\"{}\"", "newFeeAuthority", self.new_fee_authority)
            ]
            .join(",")
        )
    }
}
impl From<SetFeeAuthorityKeys>
    for [solana_instruction::AccountMeta; SET_FEE_AUTHORITY_IX_ACCOUNTS_LEN]
{
    fn from(keys: SetFeeAuthorityKeys) -> Self {
        [
            solana_instruction::AccountMeta::new(keys.whirlpools_config, false),
            solana_instruction::AccountMeta::new(keys.fee_authority, false),
            solana_instruction::AccountMeta::new(keys.new_fee_authority, false),
        ]
    }
}
pub fn set_fee_authority_ix_with_program_id(
    program_id: Pubkey,
    keys: SetFeeAuthorityKeys,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    let metas: [solana_instruction::AccountMeta; SET_FEE_AUTHORITY_IX_ACCOUNTS_LEN] = keys.into();
    let args = SetFeeAuthorityIxData::default();
    Ok(solana_instruction::Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: args.try_to_vec()?,
    })
}
pub fn set_fee_authority_ix(
    keys: SetFeeAuthorityKeys,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    set_fee_authority_ix_with_program_id(crate::ID, keys)
}
