//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!Instruction: sell_token
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const SELL_TOKEN_IX_DISCM: [u8; 8] = [109u8, 61u8, 40u8, 187u8, 230u8, 176u8, 135u8, 174u8];
pub const SELL_TOKEN_IX_ACCOUNTS_LEN: usize = 12;
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SellTokenIxData {
    pub discriminator: [u8; 8],
    pub sell_amount: u64,
    pub amount_out_min: u64,
}
impl Default for SellTokenIxData {
    fn default() -> Self {
        Self {
            discriminator: SELL_TOKEN_IX_DISCM,
            sell_amount: Default::default(),
            amount_out_min: Default::default(),
        }
    }
}
impl SellTokenIxData {
    pub fn new(sell_amount: u64, amount_out_min: u64) -> Self {
        Self {
            discriminator: Self::discriminator(),
            sell_amount,
            amount_out_min,
        }
    }
    pub fn from_bytes(buf: &[u8]) -> std::io::Result<Self> {
        borsh::BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn discriminator() -> [u8; 8] {
        SELL_TOKEN_IX_DISCM
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!(
                    "\"discriminator\":[{}]",
                    self.discriminator
                        .iter()
                        .map(|x| x.to_string())
                        .collect::<Vec<_>>()
                        .join(",")
                ),
                format!("\"{}\":{}", "sell_amount", self.sell_amount),
                format!("\"{}\":{}", "amount_out_min", self.amount_out_min)
            ]
            .join(",")
        )
    }
}
#[derive(Copy, Clone, Debug, PartialEq, Default)]
pub struct SellTokenKeys {
    pub mint: Pubkey,
    pub bonding_curve: Pubkey,
    pub trading_fees_vault: Pubkey,
    pub bonding_curve_vault: Pubkey,
    pub bonding_curve_sol_vault: Pubkey,
    pub seller_token_account: Pubkey,
    pub seller: Pubkey,
    pub recipient: Pubkey,
    pub config: Pubkey,
    pub system_program: Pubkey,
    pub token_program: Pubkey,
    pub associated_token_program: Pubkey,
}
impl From<&[Pubkey]> for SellTokenKeys {
    fn from(pubkeys: &[Pubkey]) -> Self {
        Self {
            mint: pubkeys[0],
            bonding_curve: pubkeys[1],
            trading_fees_vault: pubkeys[2],
            bonding_curve_vault: pubkeys[3],
            bonding_curve_sol_vault: pubkeys[4],
            seller_token_account: pubkeys[5],
            seller: pubkeys[6],
            recipient: pubkeys[7],
            config: pubkeys[8],
            system_program: pubkeys[9],
            token_program: pubkeys[10],
            associated_token_program: pubkeys[11],
        }
    }
}
impl SellTokenKeys {
    /// Convert Keys to Vec<Pubkey>
    pub fn to_vec(&self) -> Vec<Pubkey> {
        vec![
            self.mint,
            self.bonding_curve,
            self.trading_fees_vault,
            self.bonding_curve_vault,
            self.bonding_curve_sol_vault,
            self.seller_token_account,
            self.seller,
            self.recipient,
            self.config,
            self.system_program,
            self.token_program,
            self.associated_token_program,
        ]
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!("\"{}\":\"{}\"", "mint", self.mint),
                format!("\"{}\":\"{}\"", "bonding_curve", self.bonding_curve),
                format!(
                    "\"{}\":\"{}\"",
                    "trading_fees_vault", self.trading_fees_vault
                ),
                format!(
                    "\"{}\":\"{}\"",
                    "bonding_curve_vault", self.bonding_curve_vault
                ),
                format!(
                    "\"{}\":\"{}\"",
                    "bonding_curve_sol_vault", self.bonding_curve_sol_vault
                ),
                format!(
                    "\"{}\":\"{}\"",
                    "seller_token_account", self.seller_token_account
                ),
                format!("\"{}\":\"{}\"", "seller", self.seller),
                format!("\"{}\":\"{}\"", "recipient", self.recipient),
                format!("\"{}\":\"{}\"", "config", self.config),
                format!("\"{}\":\"{}\"", "system_program", self.system_program),
                format!("\"{}\":\"{}\"", "token_program", self.token_program),
                format!(
                    "\"{}\":\"{}\"",
                    "associated_token_program", self.associated_token_program
                )
            ]
            .join(",")
        )
    }
}
impl From<SellTokenKeys> for [solana_instruction::AccountMeta; SELL_TOKEN_IX_ACCOUNTS_LEN] {
    fn from(keys: SellTokenKeys) -> Self {
        [
            solana_instruction::AccountMeta::new(keys.mint, false),
            solana_instruction::AccountMeta::new(keys.bonding_curve, false),
            solana_instruction::AccountMeta::new(keys.trading_fees_vault, false),
            solana_instruction::AccountMeta::new(keys.bonding_curve_vault, false),
            solana_instruction::AccountMeta::new(keys.bonding_curve_sol_vault, false),
            solana_instruction::AccountMeta::new(keys.seller_token_account, false),
            solana_instruction::AccountMeta::new(keys.seller, false),
            solana_instruction::AccountMeta::new(keys.recipient, false),
            solana_instruction::AccountMeta::new(keys.config, false),
            solana_instruction::AccountMeta::new(keys.system_program, false),
            solana_instruction::AccountMeta::new(keys.token_program, false),
            solana_instruction::AccountMeta::new(keys.associated_token_program, false),
        ]
    }
}
pub fn sell_token_ix_with_program_id(
    program_id: Pubkey,
    keys: SellTokenKeys,
    args: SellTokenIxData,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    let metas: [solana_instruction::AccountMeta; SELL_TOKEN_IX_ACCOUNTS_LEN] = keys.into();
    Ok(solana_instruction::Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: args.try_to_vec()?,
    })
}
pub fn sell_token_ix(
    keys: SellTokenKeys,
    args: SellTokenIxData,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    sell_token_ix_with_program_id(crate::ID, keys, args)
}
