//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!AmmFees
///Encapsulates all fee information and calculations for swap operations
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
///Encapsulates all fee information and calculations for swap operations
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct AmmFees {
    #[cfg_attr(feature = "serde", serde(rename = "tradeFeeNumerator"))]
    pub trade_fee_numerator: u64,
    #[cfg_attr(feature = "serde", serde(rename = "tradeFeeDenominator"))]
    pub trade_fee_denominator: u64,
    #[cfg_attr(feature = "serde", serde(rename = "ownerTradeFeeNumerator"))]
    pub owner_trade_fee_numerator: u64,
    #[cfg_attr(feature = "serde", serde(rename = "ownerTradeFeeDenominator"))]
    pub owner_trade_fee_denominator: u64,
    #[cfg_attr(feature = "serde", serde(rename = "ownerWithdrawFeeNumerator"))]
    pub owner_withdraw_fee_numerator: u64,
    #[cfg_attr(feature = "serde", serde(rename = "ownerWithdrawFeeDenominator"))]
    pub owner_withdraw_fee_denominator: u64,
    #[cfg_attr(feature = "serde", serde(rename = "hostFeeNumerator"))]
    pub host_fee_numerator: u64,
    #[cfg_attr(feature = "serde", serde(rename = "hostFeeDenominator"))]
    pub host_fee_denominator: u64,
}
impl Default for AmmFees {
    fn default() -> Self {
        Self {
            trade_fee_numerator: Default::default(),
            trade_fee_denominator: Default::default(),
            owner_trade_fee_numerator: Default::default(),
            owner_trade_fee_denominator: Default::default(),
            owner_withdraw_fee_numerator: Default::default(),
            owner_withdraw_fee_denominator: Default::default(),
            host_fee_numerator: Default::default(),
            host_fee_denominator: Default::default(),
        }
    }
}
impl AmmFees {
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
        borsh::from_slice(data)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e.to_string()))
    }
}
