//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use super::*;
pub const INITIALIZE_POOL_V2_IX_ACCOUNTS_LEN: usize = 14;
///Accounts struct for the initializePoolV2 instruction
#[derive(Copy, Clone, Debug)]
pub struct InitializePoolV2Accounts<'me, 'info> {
    pub whirlpools_config: &'me AccountInfo<'info>,
    pub token_mint_a: &'me AccountInfo<'info>,
    pub token_mint_b: &'me AccountInfo<'info>,
    pub token_badge_a: &'me AccountInfo<'info>,
    pub token_badge_b: &'me AccountInfo<'info>,
    pub funder: &'me AccountInfo<'info>,
    pub whirlpool: &'me AccountInfo<'info>,
    pub token_vault_a: &'me AccountInfo<'info>,
    pub token_vault_b: &'me AccountInfo<'info>,
    pub fee_tier: &'me AccountInfo<'info>,
    pub token_program_a: &'me AccountInfo<'info>,
    pub token_program_b: &'me AccountInfo<'info>,
    pub system_program: &'me AccountInfo<'info>,
    pub rent: &'me AccountInfo<'info>,
}
///Public keys struct for the initializePoolV2 instruction
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct InitializePoolV2Keys {
    pub whirlpools_config: Pubkey,
    pub token_mint_a: Pubkey,
    pub token_mint_b: Pubkey,
    pub token_badge_a: Pubkey,
    pub token_badge_b: Pubkey,
    pub funder: Pubkey,
    pub whirlpool: Pubkey,
    pub token_vault_a: Pubkey,
    pub token_vault_b: Pubkey,
    pub fee_tier: Pubkey,
    pub token_program_a: Pubkey,
    pub token_program_b: Pubkey,
    pub system_program: Pubkey,
    pub rent: Pubkey,
}
impl From<InitializePoolV2Accounts<'_, '_>> for InitializePoolV2Keys {
    fn from(accounts: InitializePoolV2Accounts) -> Self {
        Self {
            whirlpools_config: *accounts.whirlpools_config.key,
            token_mint_a: *accounts.token_mint_a.key,
            token_mint_b: *accounts.token_mint_b.key,
            token_badge_a: *accounts.token_badge_a.key,
            token_badge_b: *accounts.token_badge_b.key,
            funder: *accounts.funder.key,
            whirlpool: *accounts.whirlpool.key,
            token_vault_a: *accounts.token_vault_a.key,
            token_vault_b: *accounts.token_vault_b.key,
            fee_tier: *accounts.fee_tier.key,
            token_program_a: *accounts.token_program_a.key,
            token_program_b: *accounts.token_program_b.key,
            system_program: *accounts.system_program.key,
            rent: *accounts.rent.key,
        }
    }
}
impl From<InitializePoolV2Keys> for [AccountMeta; INITIALIZE_POOL_V2_IX_ACCOUNTS_LEN] {
    fn from(keys: InitializePoolV2Keys) -> Self {
        [
            AccountMeta {
                pubkey: keys.whirlpools_config,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.token_mint_a,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.token_mint_b,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.token_badge_a,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.token_badge_b,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.funder,
                is_signer: true,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.whirlpool,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.token_vault_a,
                is_signer: true,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.token_vault_b,
                is_signer: true,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.fee_tier,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.token_program_a,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.token_program_b,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.system_program,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.rent,
                is_signer: false,
                is_writable: false,
            },
        ]
    }
}
impl From<[Pubkey; INITIALIZE_POOL_V2_IX_ACCOUNTS_LEN]> for InitializePoolV2Keys {
    fn from(pubkeys: [Pubkey; INITIALIZE_POOL_V2_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            whirlpools_config: pubkeys[0],
            token_mint_a: pubkeys[1],
            token_mint_b: pubkeys[2],
            token_badge_a: pubkeys[3],
            token_badge_b: pubkeys[4],
            funder: pubkeys[5],
            whirlpool: pubkeys[6],
            token_vault_a: pubkeys[7],
            token_vault_b: pubkeys[8],
            fee_tier: pubkeys[9],
            token_program_a: pubkeys[10],
            token_program_b: pubkeys[11],
            system_program: pubkeys[12],
            rent: pubkeys[13],
        }
    }
}
impl From<&[String]> for InitializePoolV2Keys {
    fn from(pubkeys: &[String]) -> Self {
        Self {
            whirlpools_config: pubkeys[0].parse().unwrap(),
            token_mint_a: pubkeys[1].parse().unwrap(),
            token_mint_b: pubkeys[2].parse().unwrap(),
            token_badge_a: pubkeys[3].parse().unwrap(),
            token_badge_b: pubkeys[4].parse().unwrap(),
            funder: pubkeys[5].parse().unwrap(),
            whirlpool: pubkeys[6].parse().unwrap(),
            token_vault_a: pubkeys[7].parse().unwrap(),
            token_vault_b: pubkeys[8].parse().unwrap(),
            fee_tier: pubkeys[9].parse().unwrap(),
            token_program_a: pubkeys[10].parse().unwrap(),
            token_program_b: pubkeys[11].parse().unwrap(),
            system_program: pubkeys[12].parse().unwrap(),
            rent: pubkeys[13].parse().unwrap(),
        }
    }
}
impl<'info> From<InitializePoolV2Accounts<'_, 'info>>
    for [AccountInfo<'info>; INITIALIZE_POOL_V2_IX_ACCOUNTS_LEN]
{
    fn from(accounts: InitializePoolV2Accounts<'_, 'info>) -> Self {
        [
            accounts.whirlpools_config.clone(),
            accounts.token_mint_a.clone(),
            accounts.token_mint_b.clone(),
            accounts.token_badge_a.clone(),
            accounts.token_badge_b.clone(),
            accounts.funder.clone(),
            accounts.whirlpool.clone(),
            accounts.token_vault_a.clone(),
            accounts.token_vault_b.clone(),
            accounts.fee_tier.clone(),
            accounts.token_program_a.clone(),
            accounts.token_program_b.clone(),
            accounts.system_program.clone(),
            accounts.rent.clone(),
        ]
    }
}
impl<'me, 'info> From<&'me [AccountInfo<'info>; INITIALIZE_POOL_V2_IX_ACCOUNTS_LEN]>
    for InitializePoolV2Accounts<'me, 'info>
{
    fn from(arr: &'me [AccountInfo<'info>; INITIALIZE_POOL_V2_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            whirlpools_config: &arr[0],
            token_mint_a: &arr[1],
            token_mint_b: &arr[2],
            token_badge_a: &arr[3],
            token_badge_b: &arr[4],
            funder: &arr[5],
            whirlpool: &arr[6],
            token_vault_a: &arr[7],
            token_vault_b: &arr[8],
            fee_tier: &arr[9],
            token_program_a: &arr[10],
            token_program_b: &arr[11],
            system_program: &arr[12],
            rent: &arr[13],
        }
    }
}
pub const INITIALIZE_POOL_V2_IX_DISCM: u8 = 36u8;
///Arguments for the initializePoolV2 instruction
#[derive(BorshDeserialize, BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitializePoolV2IxArgs {
    pub discriminator: u8,
    pub tick_spacing: u16,
    pub initial_sqrt_price: u128,
}
impl Default for InitializePoolV2IxArgs {
    fn default() -> Self {
        Self {
            discriminator: 36u8,
            tick_spacing: Default::default(),
            initial_sqrt_price: Default::default(),
        }
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct InitializePoolV2IxData(pub InitializePoolV2IxArgs);
impl From<InitializePoolV2IxArgs> for InitializePoolV2IxData {
    fn from(args: InitializePoolV2IxArgs) -> Self {
        Self(args)
    }
}
impl InitializePoolV2IxData {
    pub fn deserialize(buf: &[u8]) -> std::io::Result<Self> {
        if buf.is_empty() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Instruction data is empty",
            ));
        }
        let maybe_discm = buf[0];
        if maybe_discm != INITIALIZE_POOL_V2_IX_DISCM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "discm does not match. Expected: {}. Received: {}",
                    INITIALIZE_POOL_V2_IX_DISCM, maybe_discm
                ),
            ));
        }
        let mut reader = &buf[1..];
        Ok(Self(InitializePoolV2IxArgs::deserialize(&mut reader)?))
    }
    pub fn serialize<W: std::io::Write>(&self, mut writer: W) -> std::io::Result<()> {
        writer.write_all(&[INITIALIZE_POOL_V2_IX_DISCM])?;
        self.0.serialize(&mut writer)
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        let mut data = Vec::new();
        self.serialize(&mut data)?;
        Ok(data)
    }
}
pub fn initialize_pool_v2_ix_with_program_id(
    program_id: Pubkey,
    keys: InitializePoolV2Keys,
    args: InitializePoolV2IxArgs,
) -> std::io::Result<Instruction> {
    let metas: [AccountMeta; INITIALIZE_POOL_V2_IX_ACCOUNTS_LEN] = keys.into();
    let data: InitializePoolV2IxData = args.into();
    Ok(Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: data.try_to_vec()?,
    })
}
pub fn initialize_pool_v2_ix(
    keys: InitializePoolV2Keys,
    args: InitializePoolV2IxArgs,
) -> std::io::Result<Instruction> {
    initialize_pool_v2_ix_with_program_id(crate::ID, keys, args)
}
pub fn initialize_pool_v2_invoke_with_program_id(
    program_id: Pubkey,
    accounts: InitializePoolV2Accounts<'_, '_>,
    args: InitializePoolV2IxArgs,
) -> ProgramResult {
    let keys: InitializePoolV2Keys = accounts.into();
    let ix = initialize_pool_v2_ix_with_program_id(program_id, keys, args)?;
    invoke_instruction(&ix, accounts)
}
pub fn initialize_pool_v2_invoke(
    accounts: InitializePoolV2Accounts<'_, '_>,
    args: InitializePoolV2IxArgs,
) -> ProgramResult {
    initialize_pool_v2_invoke_with_program_id(crate::ID, accounts, args)
}
pub fn initialize_pool_v2_invoke_signed_with_program_id(
    program_id: Pubkey,
    accounts: InitializePoolV2Accounts<'_, '_>,
    args: InitializePoolV2IxArgs,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    let keys: InitializePoolV2Keys = accounts.into();
    let ix = initialize_pool_v2_ix_with_program_id(program_id, keys, args)?;
    invoke_instruction_signed(&ix, accounts, seeds)
}
pub fn initialize_pool_v2_invoke_signed(
    accounts: InitializePoolV2Accounts<'_, '_>,
    args: InitializePoolV2IxArgs,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    initialize_pool_v2_invoke_signed_with_program_id(crate::ID, accounts, args, seeds)
}
pub fn initialize_pool_v2_verify_account_keys(
    accounts: InitializePoolV2Accounts<'_, '_>,
    keys: InitializePoolV2Keys,
) -> Result<(), (Pubkey, Pubkey)> {
    for (actual, expected) in [
        (*accounts.whirlpools_config.key, keys.whirlpools_config),
        (*accounts.token_mint_a.key, keys.token_mint_a),
        (*accounts.token_mint_b.key, keys.token_mint_b),
        (*accounts.token_badge_a.key, keys.token_badge_a),
        (*accounts.token_badge_b.key, keys.token_badge_b),
        (*accounts.funder.key, keys.funder),
        (*accounts.whirlpool.key, keys.whirlpool),
        (*accounts.token_vault_a.key, keys.token_vault_a),
        (*accounts.token_vault_b.key, keys.token_vault_b),
        (*accounts.fee_tier.key, keys.fee_tier),
        (*accounts.token_program_a.key, keys.token_program_a),
        (*accounts.token_program_b.key, keys.token_program_b),
        (*accounts.system_program.key, keys.system_program),
        (*accounts.rent.key, keys.rent),
    ] {
        if actual != expected {
            return Err((actual, expected));
        }
    }
    Ok(())
}
impl InitializePoolV2IxArgs {
    pub fn serialize<W: std::io::Write>(&self, mut writer: W) -> std::io::Result<()> {
        BorshSerialize::serialize(self, &mut writer)
    }
    pub fn deserialize(buf: &[u8]) -> std::io::Result<Self> {
        BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
}
impl From<InitializePoolV2IxArgs> for WhirlpoolProgramIx {
    fn from(args: InitializePoolV2IxArgs) -> Self {
        Self::InitializePoolV2(args)
    }
}
