//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use super::*;
pub const INITIALIZE_TICK_ARRAY_IX_ACCOUNTS_LEN: usize = 4;
///Accounts struct for the initializeTickArray instruction
#[derive(Copy, Clone, Debug)]
pub struct InitializeTickArrayAccounts<'me, 'info> {
    pub whirlpool: &'me AccountInfo<'info>,
    pub funder: &'me AccountInfo<'info>,
    pub tick_array: &'me AccountInfo<'info>,
    pub system_program: &'me AccountInfo<'info>,
}
///Public keys struct for the initializeTickArray instruction
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct InitializeTickArrayKeys {
    pub whirlpool: Pubkey,
    pub funder: Pubkey,
    pub tick_array: Pubkey,
    pub system_program: Pubkey,
}
impl From<InitializeTickArrayAccounts<'_, '_>> for InitializeTickArrayKeys {
    fn from(accounts: InitializeTickArrayAccounts) -> Self {
        Self {
            whirlpool: *accounts.whirlpool.key,
            funder: *accounts.funder.key,
            tick_array: *accounts.tick_array.key,
            system_program: *accounts.system_program.key,
        }
    }
}
impl From<InitializeTickArrayKeys> for [AccountMeta; INITIALIZE_TICK_ARRAY_IX_ACCOUNTS_LEN] {
    fn from(keys: InitializeTickArrayKeys) -> Self {
        [
            AccountMeta {
                pubkey: keys.whirlpool,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.funder,
                is_signer: true,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.tick_array,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.system_program,
                is_signer: false,
                is_writable: false,
            },
        ]
    }
}
impl From<[Pubkey; INITIALIZE_TICK_ARRAY_IX_ACCOUNTS_LEN]> for InitializeTickArrayKeys {
    fn from(pubkeys: [Pubkey; INITIALIZE_TICK_ARRAY_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            whirlpool: pubkeys[0],
            funder: pubkeys[1],
            tick_array: pubkeys[2],
            system_program: pubkeys[3],
        }
    }
}
impl From<&[String]> for InitializeTickArrayKeys {
    fn from(pubkeys: &[String]) -> Self {
        Self {
            whirlpool: pubkeys[0].parse().unwrap(),
            funder: pubkeys[1].parse().unwrap(),
            tick_array: pubkeys[2].parse().unwrap(),
            system_program: pubkeys[3].parse().unwrap(),
        }
    }
}
impl<'info> From<InitializeTickArrayAccounts<'_, 'info>>
    for [AccountInfo<'info>; INITIALIZE_TICK_ARRAY_IX_ACCOUNTS_LEN]
{
    fn from(accounts: InitializeTickArrayAccounts<'_, 'info>) -> Self {
        [
            accounts.whirlpool.clone(),
            accounts.funder.clone(),
            accounts.tick_array.clone(),
            accounts.system_program.clone(),
        ]
    }
}
impl<'me, 'info> From<&'me [AccountInfo<'info>; INITIALIZE_TICK_ARRAY_IX_ACCOUNTS_LEN]>
    for InitializeTickArrayAccounts<'me, 'info>
{
    fn from(arr: &'me [AccountInfo<'info>; INITIALIZE_TICK_ARRAY_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            whirlpool: &arr[0],
            funder: &arr[1],
            tick_array: &arr[2],
            system_program: &arr[3],
        }
    }
}
pub const INITIALIZE_TICK_ARRAY_IX_DISCM: u8 = 2u8;
///Arguments for the initializeTickArray instruction
#[derive(BorshDeserialize, BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitializeTickArrayIxArgs {
    pub discriminator: u8,
    pub start_tick_index: i32,
}
impl Default for InitializeTickArrayIxArgs {
    fn default() -> Self {
        Self {
            discriminator: 2u8,
            start_tick_index: Default::default(),
        }
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct InitializeTickArrayIxData(pub InitializeTickArrayIxArgs);
impl From<InitializeTickArrayIxArgs> for InitializeTickArrayIxData {
    fn from(args: InitializeTickArrayIxArgs) -> Self {
        Self(args)
    }
}
impl InitializeTickArrayIxData {
    pub fn deserialize(buf: &[u8]) -> std::io::Result<Self> {
        if buf.is_empty() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Instruction data is empty",
            ));
        }
        let maybe_discm = buf[0];
        if maybe_discm != INITIALIZE_TICK_ARRAY_IX_DISCM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "discm does not match. Expected: {}. Received: {}",
                    INITIALIZE_TICK_ARRAY_IX_DISCM, maybe_discm
                ),
            ));
        }
        let mut reader = &buf[1..];
        Ok(Self(InitializeTickArrayIxArgs::deserialize(&mut reader)?))
    }
    pub fn serialize<W: std::io::Write>(&self, mut writer: W) -> std::io::Result<()> {
        writer.write_all(&[INITIALIZE_TICK_ARRAY_IX_DISCM])?;
        self.0.serialize(&mut writer)
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        let mut data = Vec::new();
        self.serialize(&mut data)?;
        Ok(data)
    }
}
pub fn initialize_tick_array_ix_with_program_id(
    program_id: Pubkey,
    keys: InitializeTickArrayKeys,
    args: InitializeTickArrayIxArgs,
) -> std::io::Result<Instruction> {
    let metas: [AccountMeta; INITIALIZE_TICK_ARRAY_IX_ACCOUNTS_LEN] = keys.into();
    let data: InitializeTickArrayIxData = args.into();
    Ok(Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: data.try_to_vec()?,
    })
}
pub fn initialize_tick_array_ix(
    keys: InitializeTickArrayKeys,
    args: InitializeTickArrayIxArgs,
) -> std::io::Result<Instruction> {
    initialize_tick_array_ix_with_program_id(crate::ID, keys, args)
}
pub fn initialize_tick_array_invoke_with_program_id(
    program_id: Pubkey,
    accounts: InitializeTickArrayAccounts<'_, '_>,
    args: InitializeTickArrayIxArgs,
) -> ProgramResult {
    let keys: InitializeTickArrayKeys = accounts.into();
    let ix = initialize_tick_array_ix_with_program_id(program_id, keys, args)?;
    invoke_instruction(&ix, accounts)
}
pub fn initialize_tick_array_invoke(
    accounts: InitializeTickArrayAccounts<'_, '_>,
    args: InitializeTickArrayIxArgs,
) -> ProgramResult {
    initialize_tick_array_invoke_with_program_id(crate::ID, accounts, args)
}
pub fn initialize_tick_array_invoke_signed_with_program_id(
    program_id: Pubkey,
    accounts: InitializeTickArrayAccounts<'_, '_>,
    args: InitializeTickArrayIxArgs,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    let keys: InitializeTickArrayKeys = accounts.into();
    let ix = initialize_tick_array_ix_with_program_id(program_id, keys, args)?;
    invoke_instruction_signed(&ix, accounts, seeds)
}
pub fn initialize_tick_array_invoke_signed(
    accounts: InitializeTickArrayAccounts<'_, '_>,
    args: InitializeTickArrayIxArgs,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    initialize_tick_array_invoke_signed_with_program_id(crate::ID, accounts, args, seeds)
}
pub fn initialize_tick_array_verify_account_keys(
    accounts: InitializeTickArrayAccounts<'_, '_>,
    keys: InitializeTickArrayKeys,
) -> Result<(), (Pubkey, Pubkey)> {
    for (actual, expected) in [
        (*accounts.whirlpool.key, keys.whirlpool),
        (*accounts.funder.key, keys.funder),
        (*accounts.tick_array.key, keys.tick_array),
        (*accounts.system_program.key, keys.system_program),
    ] {
        if actual != expected {
            return Err((actual, expected));
        }
    }
    Ok(())
}
impl InitializeTickArrayIxArgs {
    pub fn serialize<W: std::io::Write>(&self, mut writer: W) -> std::io::Result<()> {
        BorshSerialize::serialize(self, &mut writer)
    }
    pub fn deserialize(buf: &[u8]) -> std::io::Result<Self> {
        BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
}
impl From<InitializeTickArrayIxArgs> for WhirlpoolProgramIx {
    fn from(args: InitializeTickArrayIxArgs) -> Self {
        Self::InitializeTickArray(args)
    }
}
