//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use super::*;
///Create virtual pool metadata
#[derive(Clone, Debug, BorshDeserialize, BorshSerialize, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct EvtVirtualPoolMetadata {
    pub virtual_pool_metadata: Pubkey,
    pub virtual_pool: Pubkey,
}
pub const EVT_VIRTUAL_POOL_METADATA_EVENT_DISCM: [u8; 8] = [188, 18, 72, 76, 195, 91, 38, 74];
///Event wrapper for EvtVirtualPoolMetadata with discriminator for serialization
#[derive(Clone, Debug, PartialEq)]
pub struct EvtVirtualPoolMetadataEvent(pub EvtVirtualPoolMetadata);
impl BorshSerialize for EvtVirtualPoolMetadataEvent {
    fn serialize<W: std::io::Write>(&self, writer: &mut W) -> std::io::Result<()> {
        EVT_VIRTUAL_POOL_METADATA_EVENT_DISCM.serialize(writer)?;
        self.0.serialize(writer)
    }
}
impl EvtVirtualPoolMetadataEvent {
    pub fn deserialize(buf: &mut &[u8]) -> std::io::Result<Self> {
        let maybe_discm = <[u8; 8]>::deserialize(buf)?;
        if maybe_discm != EVT_VIRTUAL_POOL_METADATA_EVENT_DISCM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "discm does not match. Expected: {:?}. Received: {:?}",
                    EVT_VIRTUAL_POOL_METADATA_EVENT_DISCM, maybe_discm
                ),
            ));
        }
        Ok(Self(EvtVirtualPoolMetadata::deserialize(buf)?))
    }
}
