//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use super::*;
///Event emitted by EvtClaimProtocolFee
#[derive(Clone, Debug, BorshDeserialize, BorshSerialize, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct EvtClaimProtocolFee {
    pub pool: Pubkey,
    pub token_base_amount: u64,
    pub token_quote_amount: u64,
}
pub const EVT_CLAIM_PROTOCOL_FEE_EVENT_DISCM: [u8; 8] = [186, 244, 75, 251, 188, 13, 25, 33];
///Event wrapper for EvtClaimProtocolFee with discriminator for serialization
#[derive(Clone, Debug, PartialEq)]
pub struct EvtClaimProtocolFeeEvent(pub EvtClaimProtocolFee);
impl BorshSerialize for EvtClaimProtocolFeeEvent {
    fn serialize<W: std::io::Write>(&self, writer: &mut W) -> std::io::Result<()> {
        EVT_CLAIM_PROTOCOL_FEE_EVENT_DISCM.serialize(writer)?;
        self.0.serialize(writer)
    }
}
impl EvtClaimProtocolFeeEvent {
    pub fn deserialize(buf: &mut &[u8]) -> std::io::Result<Self> {
        let maybe_discm = <[u8; 8]>::deserialize(buf)?;
        if maybe_discm != EVT_CLAIM_PROTOCOL_FEE_EVENT_DISCM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "discm does not match. Expected: {:?}. Received: {:?}",
                    EVT_CLAIM_PROTOCOL_FEE_EVENT_DISCM, maybe_discm
                ),
            ));
        }
        Ok(Self(EvtClaimProtocolFee::deserialize(buf)?))
    }
}
