//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!Instruction: CancelAllOrdersWithFreeFunds (NonAnchor)
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const CANCEL_ALL_ORDERS_WITH_FREE_FUNDS_IX_DISCM: u8 = 7u8;
pub const CANCEL_ALL_ORDERS_WITH_FREE_FUNDS_IX_ACCOUNTS_LEN: usize = 4;
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CancelAllOrdersWithFreeFundsIxData {
    pub discriminator: u8,
}
impl Default for CancelAllOrdersWithFreeFundsIxData {
    fn default() -> Self {
        Self {
            discriminator: CANCEL_ALL_ORDERS_WITH_FREE_FUNDS_IX_DISCM,
        }
    }
}
impl CancelAllOrdersWithFreeFundsIxData {
    pub fn new() -> Self {
        Self {
            discriminator: Self::discriminator(),
        }
    }
    pub fn from_bytes(buf: &[u8]) -> std::io::Result<Self> {
        borsh::BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn discriminator() -> u8 {
        CANCEL_ALL_ORDERS_WITH_FREE_FUNDS_IX_DISCM
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [format!("\"discriminator\":{}", self.discriminator)].join(",")
        )
    }
}
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct CancelAllOrdersWithFreeFundsKeys {
    pub phoenix_program: Pubkey,
    pub log_authority: Pubkey,
    pub market: Pubkey,
    pub trader: Pubkey,
}
impl Default for CancelAllOrdersWithFreeFundsKeys {
    fn default() -> Self {
        Self {
            phoenix_program: Pubkey::default(),
            log_authority: Pubkey::default(),
            market: Pubkey::default(),
            trader: Pubkey::default(),
        }
    }
}
impl From<&[Pubkey]> for CancelAllOrdersWithFreeFundsKeys {
    fn from(pubkeys: &[Pubkey]) -> Self {
        Self {
            phoenix_program: pubkeys[0],
            log_authority: pubkeys[1],
            market: pubkeys[2],
            trader: pubkeys[3],
        }
    }
}
impl CancelAllOrdersWithFreeFundsKeys {
    /// Convert Keys to Vec<Pubkey>
    pub fn to_vec(&self) -> Vec<Pubkey> {
        vec![
            self.phoenix_program,
            self.log_authority,
            self.market,
            self.trader,
        ]
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!(
                    "\"{}\":{}",
                    "phoenixProgram",
                    serde_json::to_string(&self.phoenix_program)
                        .unwrap_or_else(|_| "\"null\"".to_string())
                ),
                format!(
                    "\"{}\":{}",
                    "logAuthority",
                    serde_json::to_string(&self.log_authority)
                        .unwrap_or_else(|_| "\"null\"".to_string())
                ),
                format!(
                    "\"{}\":{}",
                    "market",
                    serde_json::to_string(&self.market).unwrap_or_else(|_| "\"null\"".to_string())
                ),
                format!(
                    "\"{}\":{}",
                    "trader",
                    serde_json::to_string(&self.trader).unwrap_or_else(|_| "\"null\"".to_string())
                )
            ]
            .join(",")
        )
    }
}
impl From<CancelAllOrdersWithFreeFundsKeys>
    for [solana_instruction::AccountMeta; CANCEL_ALL_ORDERS_WITH_FREE_FUNDS_IX_ACCOUNTS_LEN]
{
    fn from(keys: CancelAllOrdersWithFreeFundsKeys) -> Self {
        [
            solana_instruction::AccountMeta::new(keys.phoenix_program, false),
            solana_instruction::AccountMeta::new(keys.log_authority, false),
            solana_instruction::AccountMeta::new(keys.market, false),
            solana_instruction::AccountMeta::new(keys.trader, false),
        ]
    }
}
pub fn cancel_all_orders_with_free_funds_ix_with_program_id(
    program_id: Pubkey,
    keys: CancelAllOrdersWithFreeFundsKeys,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    let metas: [solana_instruction::AccountMeta;
        CANCEL_ALL_ORDERS_WITH_FREE_FUNDS_IX_ACCOUNTS_LEN] = keys.into();
    Ok(solana_instruction::Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: CancelAllOrdersWithFreeFundsIxData::default().try_to_vec()?,
    })
}
pub fn cancel_all_orders_with_free_funds_ix(
    keys: CancelAllOrdersWithFreeFundsKeys,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    cancel_all_orders_with_free_funds_ix_with_program_id(crate::ID, keys)
}
