//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!Type: CancelMultipleOrdersByIdParams (NonAnchor)
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const CANCEL_MULTIPLE_ORDERS_BY_ID_PARAMS_TYPE_DISCM: u8 = 13u8;
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CancelMultipleOrdersByIdParams {
    pub orders: Vec<crate::types::CancelOrderParams>,
}
impl Default for CancelMultipleOrdersByIdParams {
    fn default() -> Self {
        Self { orders: Vec::new() }
    }
}
impl CancelMultipleOrdersByIdParams {
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
        borsh::from_slice(data)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e.to_string()))
    }
}
