//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//! Anchor events module
//! Generated event definitions with 8-byte discriminator support
//! Each event is defined in its own file
pub mod authority_transfer_cancelled_event;
pub mod authority_transfer_completed_event;
pub mod authority_transfer_initiated_event;
pub mod bonding_curve_deployed_event;
pub mod bonding_curve_deployed_fallback_event;
pub mod bonding_curve_vault_closed_event;
pub mod config_updated_event;
pub mod liquidity_deposited_into_raydium_event;
pub mod operators_added_event;
pub mod operators_removed_event;
pub mod paused_toggled_event;
pub mod raydium_liquidity_locked_event;
pub mod raydium_pool_created_event;
pub mod raydium_random_pool_created_event;
pub mod swap_sol_for_tokens_on_raydium_event;
pub mod swap_tokens_for_sol_on_raydium_event;
pub mod token_bought_event;
pub mod token_created_event;
pub mod token_created_fallback_event;
pub mod token_graduated_event;
pub mod token_sold_event;
pub mod trading_fees_collected_event;
pub mod trading_fees_split_event;
pub use authority_transfer_cancelled_event::*;
pub use authority_transfer_completed_event::*;
pub use authority_transfer_initiated_event::*;
pub use bonding_curve_deployed_event::*;
pub use bonding_curve_deployed_fallback_event::*;
pub use bonding_curve_vault_closed_event::*;
pub use config_updated_event::*;
pub use liquidity_deposited_into_raydium_event::*;
pub use operators_added_event::*;
pub use operators_removed_event::*;
pub use paused_toggled_event::*;
pub use raydium_liquidity_locked_event::*;
pub use raydium_pool_created_event::*;
pub use raydium_random_pool_created_event::*;
pub use swap_sol_for_tokens_on_raydium_event::*;
pub use swap_tokens_for_sol_on_raydium_event::*;
pub use token_bought_event::*;
pub use token_created_event::*;
pub use token_created_fallback_event::*;
pub use token_graduated_event::*;
pub use token_sold_event::*;
pub use trading_fees_collected_event::*;
pub use trading_fees_split_event::*;
