//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use borsh::{BorshDeserialize, BorshSerialize};
#[derive(Clone, Debug, BorshDeserialize, BorshSerialize, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BatchCreateArgs {
    ///Index of the vault this transaction belongs to.
    pub vault_index: u8,
    pub memo: Option<String>,
}
impl Default for BatchCreateArgs {
    fn default() -> Self {
        Self {
            vault_index: Default::default(),
            memo: None,
        }
    }
}
