//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//! Non-Anchor parser module
//! Generated parsers for instructions and accounts with 1-byte discriminator and length-based identification
pub mod accounts;
pub mod instructions;
pub use accounts::*;
pub use instructions::*;
