//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!Instruction: approve_strategy
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const APPROVE_STRATEGY_IX_DISCM: [u8; 8] = [7u8, 141u8, 162u8, 60u8, 71u8, 115u8, 26u8, 146u8];
pub const APPROVE_STRATEGY_IX_ACCOUNTS_LEN: usize = 2;
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ApproveStrategyIxData {
    pub discriminator: [u8; 8],
}
impl Default for ApproveStrategyIxData {
    fn default() -> Self {
        Self {
            discriminator: APPROVE_STRATEGY_IX_DISCM,
        }
    }
}
impl ApproveStrategyIxData {
    pub fn new() -> Self {
        Self {
            discriminator: Self::discriminator(),
        }
    }
    pub fn from_bytes(buf: &[u8]) -> std::io::Result<Self> {
        borsh::BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn discriminator() -> [u8; 8] {
        APPROVE_STRATEGY_IX_DISCM
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [format!(
                "\"discriminator\":[{}]",
                self.discriminator
                    .iter()
                    .map(|x| x.to_string())
                    .collect::<Vec<_>>()
                    .join(",")
            )]
            .join(",")
        )
    }
}
#[derive(Copy, Clone, Debug, PartialEq, Default)]
pub struct ApproveStrategyKeys {
    pub admin_only: Pubkey,
    pub strategy: Pubkey,
}
impl From<&[Pubkey]> for ApproveStrategyKeys {
    fn from(pubkeys: &[Pubkey]) -> Self {
        Self {
            admin_only: pubkeys[0],
            strategy: pubkeys[1],
        }
    }
}
impl ApproveStrategyKeys {
    /// Convert Keys to Vec<Pubkey>
    pub fn to_vec(&self) -> Vec<Pubkey> {
        vec![self.admin_only, self.strategy]
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!("\"{}\":\"{}\"", "admin_only", self.admin_only),
                format!("\"{}\":\"{}\"", "strategy", self.strategy)
            ]
            .join(",")
        )
    }
}
impl From<ApproveStrategyKeys>
    for [solana_instruction::AccountMeta; APPROVE_STRATEGY_IX_ACCOUNTS_LEN]
{
    fn from(keys: ApproveStrategyKeys) -> Self {
        [
            solana_instruction::AccountMeta::new(keys.admin_only, false),
            solana_instruction::AccountMeta::new(keys.strategy, false),
        ]
    }
}
pub fn approve_strategy_ix_with_program_id(
    program_id: Pubkey,
    keys: ApproveStrategyKeys,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    let metas: [solana_instruction::AccountMeta; APPROVE_STRATEGY_IX_ACCOUNTS_LEN] = keys.into();
    let args = ApproveStrategyIxData::default();
    Ok(solana_instruction::Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: args.try_to_vec()?,
    })
}
pub fn approve_strategy_ix(
    keys: ApproveStrategyKeys,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    approve_strategy_ix_with_program_id(crate::ID, keys)
}
