//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!Instruction: initialize
///initialize a pool
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const INITIALIZE_IX_DISCM: [u8; 8] = [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8];
pub const INITIALIZE_IX_ACCOUNTS_LEN: usize = 6;
///initialize a pool
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InitializeIxData {
    pub discriminator: [u8; 8],
    pub amp_factor: u16,
    pub swap_fee: u64,
    pub max_caps: Vec<u64>,
}
impl Default for InitializeIxData {
    fn default() -> Self {
        Self {
            discriminator: INITIALIZE_IX_DISCM,
            amp_factor: Default::default(),
            swap_fee: Default::default(),
            max_caps: Default::default(),
        }
    }
}
impl InitializeIxData {
    pub fn new(amp_factor: u16, swap_fee: u64, max_caps: Vec<u64>) -> Self {
        Self {
            discriminator: Self::discriminator(),
            amp_factor,
            swap_fee,
            max_caps,
        }
    }
    pub fn from_bytes(buf: &[u8]) -> std::io::Result<Self> {
        borsh::BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn discriminator() -> [u8; 8] {
        INITIALIZE_IX_DISCM
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!(
                    "\"discriminator\":[{}]",
                    self.discriminator
                        .iter()
                        .map(|x| x.to_string())
                        .collect::<Vec<_>>()
                        .join(",")
                ),
                format!("\"{}\":{}", "amp_factor", self.amp_factor),
                format!("\"{}\":{}", "swap_fee", self.swap_fee),
                format!("\"{}\":{}", "max_caps", self.max_caps)
            ]
            .join(",")
        )
    }
}
#[derive(Copy, Clone, Debug, PartialEq, Default)]
pub struct InitializeKeys {
    pub owner: Pubkey,
    pub mint: Pubkey,
    pub pool: Pubkey,
    pub pool_authority: Pubkey,
    pub withdraw_authority: Pubkey,
    pub vault: Pubkey,
}
impl From<&[Pubkey]> for InitializeKeys {
    fn from(pubkeys: &[Pubkey]) -> Self {
        Self {
            owner: pubkeys[0],
            mint: pubkeys[1],
            pool: pubkeys[2],
            pool_authority: pubkeys[3],
            withdraw_authority: pubkeys[4],
            vault: pubkeys[5],
        }
    }
}
impl InitializeKeys {
    /// Convert Keys to Vec<Pubkey>
    pub fn to_vec(&self) -> Vec<Pubkey> {
        vec![
            self.owner,
            self.mint,
            self.pool,
            self.pool_authority,
            self.withdraw_authority,
            self.vault,
        ]
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!("\"{}\":\"{}\"", "owner", self.owner),
                format!("\"{}\":\"{}\"", "mint", self.mint),
                format!("\"{}\":\"{}\"", "pool", self.pool),
                format!("\"{}\":\"{}\"", "pool_authority", self.pool_authority),
                format!(
                    "\"{}\":\"{}\"",
                    "withdraw_authority", self.withdraw_authority
                ),
                format!("\"{}\":\"{}\"", "vault", self.vault)
            ]
            .join(",")
        )
    }
}
impl From<InitializeKeys> for [solana_instruction::AccountMeta; INITIALIZE_IX_ACCOUNTS_LEN] {
    fn from(keys: InitializeKeys) -> Self {
        [
            solana_instruction::AccountMeta::new(keys.owner, false),
            solana_instruction::AccountMeta::new(keys.mint, false),
            solana_instruction::AccountMeta::new(keys.pool, false),
            solana_instruction::AccountMeta::new(keys.pool_authority, false),
            solana_instruction::AccountMeta::new(keys.withdraw_authority, false),
            solana_instruction::AccountMeta::new(keys.vault, false),
        ]
    }
}
pub fn initialize_ix_with_program_id(
    program_id: Pubkey,
    keys: InitializeKeys,
    args: InitializeIxData,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    let metas: [solana_instruction::AccountMeta; INITIALIZE_IX_ACCOUNTS_LEN] = keys.into();
    Ok(solana_instruction::Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: args.try_to_vec()?,
    })
}
pub fn initialize_ix(
    keys: InitializeKeys,
    args: InitializeIxData,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    initialize_ix_with_program_id(crate::ID, keys, args)
}
