//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use super::*;
///shutdown the zero-liquidity pool
pub const SHUTDOWN_IX_ACCOUNTS_LEN: usize = 2;
///Accounts struct for the shutdown instruction
#[derive(Copy, Clone, Debug)]
pub struct ShutdownAccounts<'me, 'info> {
    pub owner: &'me AccountInfo<'info>,
    pub pool: &'me AccountInfo<'info>,
}
///Public keys struct for the shutdown instruction
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct ShutdownKeys {
    pub owner: Pubkey,
    pub pool: Pubkey,
}
impl From<ShutdownAccounts<'_, '_>> for ShutdownKeys {
    fn from(accounts: ShutdownAccounts) -> Self {
        Self {
            owner: *accounts.owner.key,
            pool: *accounts.pool.key,
        }
    }
}
impl From<ShutdownKeys> for [AccountMeta; SHUTDOWN_IX_ACCOUNTS_LEN] {
    fn from(keys: ShutdownKeys) -> Self {
        [
            AccountMeta {
                pubkey: keys.owner,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.pool,
                is_signer: false,
                is_writable: true,
            },
        ]
    }
}
impl From<[Pubkey; SHUTDOWN_IX_ACCOUNTS_LEN]> for ShutdownKeys {
    fn from(pubkeys: [Pubkey; SHUTDOWN_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            owner: pubkeys[0],
            pool: pubkeys[1],
        }
    }
}
impl From<&[String]> for ShutdownKeys {
    fn from(pubkeys: &[String]) -> Self {
        Self {
            owner: pubkeys[0].parse().unwrap(),
            pool: pubkeys[1].parse().unwrap(),
        }
    }
}
impl<'info> From<ShutdownAccounts<'_, 'info>> for [AccountInfo<'info>; SHUTDOWN_IX_ACCOUNTS_LEN] {
    fn from(accounts: ShutdownAccounts<'_, 'info>) -> Self {
        [accounts.owner.clone(), accounts.pool.clone()]
    }
}
impl<'me, 'info> From<&'me [AccountInfo<'info>; SHUTDOWN_IX_ACCOUNTS_LEN]>
    for ShutdownAccounts<'me, 'info>
{
    fn from(arr: &'me [AccountInfo<'info>; SHUTDOWN_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            owner: &arr[0],
            pool: &arr[1],
        }
    }
}
pub const SHUTDOWN_IX_DISCM: [u8; 8] = [146, 204, 241, 213, 86, 21, 253, 211];
#[derive(Clone, Debug, PartialEq)]
pub struct ShutdownIxData;
impl ShutdownIxData {
    pub fn deserialize(buf: &[u8]) -> std::io::Result<Self> {
        let mut reader = buf;
        let mut maybe_discm = [0u8; 8];
        reader.read_exact(&mut maybe_discm)?;
        if maybe_discm != SHUTDOWN_IX_DISCM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "discm does not match. Expected: {:?}. Received: {:?}",
                    SHUTDOWN_IX_DISCM, maybe_discm
                ),
            ));
        }
        Ok(Self)
    }
    pub fn serialize<W: std::io::Write>(&self, mut writer: W) -> std::io::Result<()> {
        writer.write_all(&SHUTDOWN_IX_DISCM)
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        let mut data = Vec::new();
        self.serialize(&mut data)?;
        Ok(data)
    }
}
pub fn shutdown_ix_with_program_id(
    program_id: Pubkey,
    keys: ShutdownKeys,
) -> std::io::Result<Instruction> {
    let metas: [AccountMeta; SHUTDOWN_IX_ACCOUNTS_LEN] = keys.into();
    Ok(Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: ShutdownIxData.try_to_vec()?,
    })
}
pub fn shutdown_ix(keys: ShutdownKeys) -> std::io::Result<Instruction> {
    shutdown_ix_with_program_id(crate::ID, keys)
}
pub fn shutdown_invoke_with_program_id(
    program_id: Pubkey,
    accounts: ShutdownAccounts<'_, '_>,
) -> ProgramResult {
    let keys: ShutdownKeys = accounts.into();
    let ix = shutdown_ix_with_program_id(program_id, keys)?;
    invoke_instruction(&ix, accounts)
}
pub fn shutdown_invoke(accounts: ShutdownAccounts<'_, '_>) -> ProgramResult {
    shutdown_invoke_with_program_id(crate::ID, accounts)
}
pub fn shutdown_invoke_signed_with_program_id(
    program_id: Pubkey,
    accounts: ShutdownAccounts<'_, '_>,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    let keys: ShutdownKeys = accounts.into();
    let ix = shutdown_ix_with_program_id(program_id, keys)?;
    invoke_instruction_signed(&ix, accounts, seeds)
}
pub fn shutdown_invoke_signed(
    accounts: ShutdownAccounts<'_, '_>,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    shutdown_invoke_signed_with_program_id(crate::ID, accounts, seeds)
}
pub fn shutdown_verify_account_keys(
    accounts: ShutdownAccounts<'_, '_>,
    keys: ShutdownKeys,
) -> Result<(), (Pubkey, Pubkey)> {
    for (actual, expected) in [
        (*accounts.owner.key, keys.owner),
        (*accounts.pool.key, keys.pool),
    ] {
        if actual != expected {
            return Err((actual, expected));
        }
    }
    Ok(())
}
