//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use super::*;
pub const TRANSFER_OWNER_IX_ACCOUNTS_LEN: usize = 2;
///Accounts struct for the transfer_owner instruction
#[derive(Copy, Clone, Debug)]
pub struct TransferOwnerAccounts<'me, 'info> {
    pub owner: &'me AccountInfo<'info>,
    pub pool: &'me AccountInfo<'info>,
}
///Public keys struct for the transfer_owner instruction
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct TransferOwnerKeys {
    pub owner: Pubkey,
    pub pool: Pubkey,
}
impl From<TransferOwnerAccounts<'_, '_>> for TransferOwnerKeys {
    fn from(accounts: TransferOwnerAccounts) -> Self {
        Self {
            owner: *accounts.owner.key,
            pool: *accounts.pool.key,
        }
    }
}
impl From<TransferOwnerKeys> for [AccountMeta; TRANSFER_OWNER_IX_ACCOUNTS_LEN] {
    fn from(keys: TransferOwnerKeys) -> Self {
        [
            AccountMeta {
                pubkey: keys.owner,
                is_signer: true,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.pool,
                is_signer: false,
                is_writable: true,
            },
        ]
    }
}
impl From<[Pubkey; TRANSFER_OWNER_IX_ACCOUNTS_LEN]> for TransferOwnerKeys {
    fn from(pubkeys: [Pubkey; TRANSFER_OWNER_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            owner: pubkeys[0],
            pool: pubkeys[1],
        }
    }
}
impl From<&[String]> for TransferOwnerKeys {
    fn from(pubkeys: &[String]) -> Self {
        Self {
            owner: pubkeys[0].parse().unwrap(),
            pool: pubkeys[1].parse().unwrap(),
        }
    }
}
impl<'info> From<TransferOwnerAccounts<'_, 'info>>
    for [AccountInfo<'info>; TRANSFER_OWNER_IX_ACCOUNTS_LEN]
{
    fn from(accounts: TransferOwnerAccounts<'_, 'info>) -> Self {
        [accounts.owner.clone(), accounts.pool.clone()]
    }
}
impl<'me, 'info> From<&'me [AccountInfo<'info>; TRANSFER_OWNER_IX_ACCOUNTS_LEN]>
    for TransferOwnerAccounts<'me, 'info>
{
    fn from(arr: &'me [AccountInfo<'info>; TRANSFER_OWNER_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            owner: &arr[0],
            pool: &arr[1],
        }
    }
}
pub const TRANSFER_OWNER_IX_DISCM: [u8; 8] = [245, 25, 221, 175, 106, 229, 225, 45];
///Arguments for the transfer_owner instruction
#[derive(BorshDeserialize, BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TransferOwnerIxArgs {
    pub discriminator: [u8; 8],
    pub new_owner: Pubkey,
}
impl Default for TransferOwnerIxArgs {
    fn default() -> Self {
        Self {
            discriminator: [245u8, 25u8, 221u8, 175u8, 106u8, 229u8, 225u8, 45u8],
            new_owner: Default::default(),
        }
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct TransferOwnerIxData(pub TransferOwnerIxArgs);
impl From<TransferOwnerIxArgs> for TransferOwnerIxData {
    fn from(args: TransferOwnerIxArgs) -> Self {
        Self(args)
    }
}
impl TransferOwnerIxData {
    pub fn deserialize(buf: &[u8]) -> std::io::Result<Self> {
        let mut reader = buf;
        let mut maybe_discm = [0u8; 8];
        reader.read_exact(&mut maybe_discm)?;
        if maybe_discm != TRANSFER_OWNER_IX_DISCM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "discm does not match. Expected: {:?}. Received: {:?}",
                    TRANSFER_OWNER_IX_DISCM, maybe_discm
                ),
            ));
        }
        Ok(Self(TransferOwnerIxArgs::deserialize(&mut reader)?))
    }
    pub fn serialize<W: std::io::Write>(&self, mut writer: W) -> std::io::Result<()> {
        writer.write_all(&TRANSFER_OWNER_IX_DISCM)?;
        self.0.serialize(&mut writer)
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        let mut data = Vec::new();
        self.serialize(&mut data)?;
        Ok(data)
    }
}
pub fn transfer_owner_ix_with_program_id(
    program_id: Pubkey,
    keys: TransferOwnerKeys,
    args: TransferOwnerIxArgs,
) -> std::io::Result<Instruction> {
    let metas: [AccountMeta; TRANSFER_OWNER_IX_ACCOUNTS_LEN] = keys.into();
    let data: TransferOwnerIxData = args.into();
    Ok(Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: data.try_to_vec()?,
    })
}
pub fn transfer_owner_ix(
    keys: TransferOwnerKeys,
    args: TransferOwnerIxArgs,
) -> std::io::Result<Instruction> {
    transfer_owner_ix_with_program_id(crate::ID, keys, args)
}
pub fn transfer_owner_invoke_with_program_id(
    program_id: Pubkey,
    accounts: TransferOwnerAccounts<'_, '_>,
    args: TransferOwnerIxArgs,
) -> ProgramResult {
    let keys: TransferOwnerKeys = accounts.into();
    let ix = transfer_owner_ix_with_program_id(program_id, keys, args)?;
    invoke_instruction(&ix, accounts)
}
pub fn transfer_owner_invoke(
    accounts: TransferOwnerAccounts<'_, '_>,
    args: TransferOwnerIxArgs,
) -> ProgramResult {
    transfer_owner_invoke_with_program_id(crate::ID, accounts, args)
}
pub fn transfer_owner_invoke_signed_with_program_id(
    program_id: Pubkey,
    accounts: TransferOwnerAccounts<'_, '_>,
    args: TransferOwnerIxArgs,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    let keys: TransferOwnerKeys = accounts.into();
    let ix = transfer_owner_ix_with_program_id(program_id, keys, args)?;
    invoke_instruction_signed(&ix, accounts, seeds)
}
pub fn transfer_owner_invoke_signed(
    accounts: TransferOwnerAccounts<'_, '_>,
    args: TransferOwnerIxArgs,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    transfer_owner_invoke_signed_with_program_id(crate::ID, accounts, args, seeds)
}
pub fn transfer_owner_verify_account_keys(
    accounts: TransferOwnerAccounts<'_, '_>,
    keys: TransferOwnerKeys,
) -> Result<(), (Pubkey, Pubkey)> {
    for (actual, expected) in [
        (*accounts.owner.key, keys.owner),
        (*accounts.pool.key, keys.pool),
    ] {
        if actual != expected {
            return Err((actual, expected));
        }
    }
    Ok(())
}
impl TransferOwnerIxArgs {
    pub fn serialize<W: std::io::Write>(&self, mut writer: W) -> std::io::Result<()> {
        BorshSerialize::serialize(self, &mut writer)
    }
    pub fn deserialize(buf: &[u8]) -> std::io::Result<Self> {
        BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
}
impl From<TransferOwnerIxArgs> for StableSwapProgramIx {
    fn from(args: TransferOwnerIxArgs) -> Self {
        Self::TransferOwner(args)
    }
}
