//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use super::*;
///Event emitted by BondingCurveVaultClosedEvent
#[derive(Clone, Debug, BorshDeserialize, BorshSerialize, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BondingCurveVaultClosedEvent {
    pub mint: Pubkey,
    pub recipient: Pubkey,
    pub amount: u64,
}
pub const BONDING_CURVE_VAULT_CLOSED_EVENT_EVENT_DISCM: [u8; 8] =
    [185, 36, 156, 82, 189, 164, 207, 79];
///Event wrapper for BondingCurveVaultClosedEvent with discriminator for serialization
#[derive(Clone, Debug, PartialEq)]
pub struct BondingCurveVaultClosedEventEvent(pub BondingCurveVaultClosedEvent);
impl BorshSerialize for BondingCurveVaultClosedEventEvent {
    fn serialize<W: std::io::Write>(&self, writer: &mut W) -> std::io::Result<()> {
        BONDING_CURVE_VAULT_CLOSED_EVENT_EVENT_DISCM.serialize(writer)?;
        self.0.serialize(writer)
    }
}
impl BondingCurveVaultClosedEventEvent {
    pub fn deserialize(buf: &mut &[u8]) -> std::io::Result<Self> {
        let maybe_discm = <[u8; 8]>::deserialize(buf)?;
        if maybe_discm != BONDING_CURVE_VAULT_CLOSED_EVENT_EVENT_DISCM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "discm does not match. Expected: {:?}. Received: {:?}",
                    BONDING_CURVE_VAULT_CLOSED_EVENT_EVENT_DISCM, maybe_discm
                ),
            ));
        }
        Ok(Self(BondingCurveVaultClosedEvent::deserialize(buf)?))
    }
}
