//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use super::*;
///Event emitted by TokenBoughtEvent
#[derive(Clone, Debug, BorshDeserialize, BorshSerialize, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TokenBoughtEvent {
    pub mint: Pubkey,
    pub amount_in: u64,
    pub amount_out: u64,
    pub swap_fee: u64,
    pub buyer: Pubkey,
    pub recipient: Pubkey,
}
pub const TOKEN_BOUGHT_EVENT_EVENT_DISCM: [u8; 8] = [71, 89, 222, 124, 215, 192, 230, 138];
///Event wrapper for TokenBoughtEvent with discriminator for serialization
#[derive(Clone, Debug, PartialEq)]
pub struct TokenBoughtEventEvent(pub TokenBoughtEvent);
impl BorshSerialize for TokenBoughtEventEvent {
    fn serialize<W: std::io::Write>(&self, writer: &mut W) -> std::io::Result<()> {
        TOKEN_BOUGHT_EVENT_EVENT_DISCM.serialize(writer)?;
        self.0.serialize(writer)
    }
}
impl TokenBoughtEventEvent {
    pub fn deserialize(buf: &mut &[u8]) -> std::io::Result<Self> {
        let maybe_discm = <[u8; 8]>::deserialize(buf)?;
        if maybe_discm != TOKEN_BOUGHT_EVENT_EVENT_DISCM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "discm does not match. Expected: {:?}. Received: {:?}",
                    TOKEN_BOUGHT_EVENT_EVENT_DISCM, maybe_discm
                ),
            ));
        }
        Ok(Self(TokenBoughtEvent::deserialize(buf)?))
    }
}
