//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use super::*;
///Event emitted by TradingFeesSplitEvent
#[derive(Clone, Debug, BorshDeserialize, BorshSerialize, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TradingFeesSplitEvent {
    pub amount: u64,
    pub creator: Pubkey,
}
pub const TRADING_FEES_SPLIT_EVENT_EVENT_DISCM: [u8; 8] = [113, 60, 159, 17, 253, 174, 135, 122];
///Event wrapper for TradingFeesSplitEvent with discriminator for serialization
#[derive(Clone, Debug, PartialEq)]
pub struct TradingFeesSplitEventEvent(pub TradingFeesSplitEvent);
impl BorshSerialize for TradingFeesSplitEventEvent {
    fn serialize<W: std::io::Write>(&self, writer: &mut W) -> std::io::Result<()> {
        TRADING_FEES_SPLIT_EVENT_EVENT_DISCM.serialize(writer)?;
        self.0.serialize(writer)
    }
}
impl TradingFeesSplitEventEvent {
    pub fn deserialize(buf: &mut &[u8]) -> std::io::Result<Self> {
        let maybe_discm = <[u8; 8]>::deserialize(buf)?;
        if maybe_discm != TRADING_FEES_SPLIT_EVENT_EVENT_DISCM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "discm does not match. Expected: {:?}. Received: {:?}",
                    TRADING_FEES_SPLIT_EVENT_EVENT_DISCM, maybe_discm
                ),
            ));
        }
        Ok(Self(TradingFeesSplitEvent::deserialize(buf)?))
    }
}
