//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use super::*;
///Execute a config transaction.
///The transaction must be `Approved`.
pub const CONFIG_TRANSACTION_EXECUTE_IX_ACCOUNTS_LEN: usize = 6;
///Accounts struct for the configTransactionExecute instruction
#[derive(Copy, Clone, Debug)]
pub struct ConfigTransactionExecuteAccounts<'me, 'info> {
    ///The multisig account that owns the transaction.
    pub multisig: &'me AccountInfo<'info>,
    ///One of the multisig members with `Execute` permission.
    pub member: &'me AccountInfo<'info>,
    ///The proposal account associated with the transaction.
    pub proposal: &'me AccountInfo<'info>,
    ///The transaction to execute.
    pub transaction: &'me AccountInfo<'info>,
    ///The account that will be charged/credited in case the config transaction causes space reallocation,
    ///for example when adding a new member, adding or removing a spending limit.
    ///This is usually the same as `member`, but can be a different account if needed.
    pub rent_payer: &'me AccountInfo<'info>,
    ///We might need it in case reallocation is needed.
    pub system_program: &'me AccountInfo<'info>,
}
///Public keys struct for the configTransactionExecute instruction
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct ConfigTransactionExecuteKeys {
    ///The multisig account that owns the transaction.
    pub multisig: Pubkey,
    ///One of the multisig members with `Execute` permission.
    pub member: Pubkey,
    ///The proposal account associated with the transaction.
    pub proposal: Pubkey,
    ///The transaction to execute.
    pub transaction: Pubkey,
    ///The account that will be charged/credited in case the config transaction causes space reallocation,
    ///for example when adding a new member, adding or removing a spending limit.
    ///This is usually the same as `member`, but can be a different account if needed.
    pub rent_payer: Pubkey,
    ///We might need it in case reallocation is needed.
    pub system_program: Pubkey,
}
impl From<ConfigTransactionExecuteAccounts<'_, '_>> for ConfigTransactionExecuteKeys {
    fn from(accounts: ConfigTransactionExecuteAccounts) -> Self {
        Self {
            multisig: *accounts.multisig.key,
            member: *accounts.member.key,
            proposal: *accounts.proposal.key,
            transaction: *accounts.transaction.key,
            rent_payer: *accounts.rent_payer.key,
            system_program: *accounts.system_program.key,
        }
    }
}
impl From<ConfigTransactionExecuteKeys>
    for [AccountMeta; CONFIG_TRANSACTION_EXECUTE_IX_ACCOUNTS_LEN]
{
    fn from(keys: ConfigTransactionExecuteKeys) -> Self {
        [
            AccountMeta {
                pubkey: keys.multisig,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.member,
                is_signer: true,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.proposal,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.transaction,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.rent_payer,
                is_signer: true,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.system_program,
                is_signer: false,
                is_writable: false,
            },
        ]
    }
}
impl From<[Pubkey; CONFIG_TRANSACTION_EXECUTE_IX_ACCOUNTS_LEN]> for ConfigTransactionExecuteKeys {
    fn from(pubkeys: [Pubkey; CONFIG_TRANSACTION_EXECUTE_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            multisig: pubkeys[0],
            member: pubkeys[1],
            proposal: pubkeys[2],
            transaction: pubkeys[3],
            rent_payer: pubkeys[4],
            system_program: pubkeys[5],
        }
    }
}
impl From<&[String]> for ConfigTransactionExecuteKeys {
    fn from(pubkeys: &[String]) -> Self {
        Self {
            multisig: pubkeys[0].parse().unwrap(),
            member: pubkeys[1].parse().unwrap(),
            proposal: pubkeys[2].parse().unwrap(),
            transaction: pubkeys[3].parse().unwrap(),
            rent_payer: pubkeys[4].parse().unwrap(),
            system_program: pubkeys[5].parse().unwrap(),
        }
    }
}
impl<'info> From<ConfigTransactionExecuteAccounts<'_, 'info>>
    for [AccountInfo<'info>; CONFIG_TRANSACTION_EXECUTE_IX_ACCOUNTS_LEN]
{
    fn from(accounts: ConfigTransactionExecuteAccounts<'_, 'info>) -> Self {
        [
            accounts.multisig.clone(),
            accounts.member.clone(),
            accounts.proposal.clone(),
            accounts.transaction.clone(),
            accounts.rent_payer.clone(),
            accounts.system_program.clone(),
        ]
    }
}
impl<'me, 'info> From<&'me [AccountInfo<'info>; CONFIG_TRANSACTION_EXECUTE_IX_ACCOUNTS_LEN]>
    for ConfigTransactionExecuteAccounts<'me, 'info>
{
    fn from(arr: &'me [AccountInfo<'info>; CONFIG_TRANSACTION_EXECUTE_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            multisig: &arr[0],
            member: &arr[1],
            proposal: &arr[2],
            transaction: &arr[3],
            rent_payer: &arr[4],
            system_program: &arr[5],
        }
    }
}
pub const CONFIG_TRANSACTION_EXECUTE_IX_DISCM: u8 = 15u8;
#[derive(Clone, Debug, PartialEq)]
pub struct ConfigTransactionExecuteIxData;
impl ConfigTransactionExecuteIxData {
    pub fn deserialize(buf: &[u8]) -> std::io::Result<Self> {
        if buf.is_empty() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Instruction data is empty",
            ));
        }
        let maybe_discm = buf[0];
        if maybe_discm != CONFIG_TRANSACTION_EXECUTE_IX_DISCM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "discm does not match. Expected: {}. Received: {}",
                    CONFIG_TRANSACTION_EXECUTE_IX_DISCM, maybe_discm
                ),
            ));
        }
        Ok(Self)
    }
    pub fn serialize<W: std::io::Write>(&self, mut writer: W) -> std::io::Result<()> {
        writer.write_all(&[CONFIG_TRANSACTION_EXECUTE_IX_DISCM])
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        let mut data = Vec::new();
        self.serialize(&mut data)?;
        Ok(data)
    }
}
pub fn config_transaction_execute_ix_with_program_id(
    program_id: Pubkey,
    keys: ConfigTransactionExecuteKeys,
) -> std::io::Result<Instruction> {
    let metas: [AccountMeta; CONFIG_TRANSACTION_EXECUTE_IX_ACCOUNTS_LEN] = keys.into();
    Ok(Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: ConfigTransactionExecuteIxData.try_to_vec()?,
    })
}
pub fn config_transaction_execute_ix(
    keys: ConfigTransactionExecuteKeys,
) -> std::io::Result<Instruction> {
    config_transaction_execute_ix_with_program_id(crate::ID, keys)
}
pub fn config_transaction_execute_invoke_with_program_id(
    program_id: Pubkey,
    accounts: ConfigTransactionExecuteAccounts<'_, '_>,
) -> ProgramResult {
    let keys: ConfigTransactionExecuteKeys = accounts.into();
    let ix = config_transaction_execute_ix_with_program_id(program_id, keys)?;
    invoke_instruction(&ix, accounts)
}
pub fn config_transaction_execute_invoke(
    accounts: ConfigTransactionExecuteAccounts<'_, '_>,
) -> ProgramResult {
    config_transaction_execute_invoke_with_program_id(crate::ID, accounts)
}
pub fn config_transaction_execute_invoke_signed_with_program_id(
    program_id: Pubkey,
    accounts: ConfigTransactionExecuteAccounts<'_, '_>,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    let keys: ConfigTransactionExecuteKeys = accounts.into();
    let ix = config_transaction_execute_ix_with_program_id(program_id, keys)?;
    invoke_instruction_signed(&ix, accounts, seeds)
}
pub fn config_transaction_execute_invoke_signed(
    accounts: ConfigTransactionExecuteAccounts<'_, '_>,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    config_transaction_execute_invoke_signed_with_program_id(crate::ID, accounts, seeds)
}
pub fn config_transaction_execute_verify_account_keys(
    accounts: ConfigTransactionExecuteAccounts<'_, '_>,
    keys: ConfigTransactionExecuteKeys,
) -> Result<(), (Pubkey, Pubkey)> {
    for (actual, expected) in [
        (*accounts.multisig.key, keys.multisig),
        (*accounts.member.key, keys.member),
        (*accounts.proposal.key, keys.proposal),
        (*accounts.transaction.key, keys.transaction),
        (*accounts.rent_payer.key, keys.rent_payer),
        (*accounts.system_program.key, keys.system_program),
    ] {
        if actual != expected {
            return Err((actual, expected));
        }
    }
    Ok(())
}
