//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use super::*;
///Update status of a multisig proposal from `Draft` to `Active`.
pub const PROPOSAL_ACTIVATE_IX_ACCOUNTS_LEN: usize = 3;
///Accounts struct for the proposalActivate instruction
#[derive(Copy, Clone, Debug)]
pub struct ProposalActivateAccounts<'me, 'info> {
    pub multisig: &'me AccountInfo<'info>,
    pub member: &'me AccountInfo<'info>,
    pub proposal: &'me AccountInfo<'info>,
}
///Public keys struct for the proposalActivate instruction
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct ProposalActivateKeys {
    pub multisig: Pubkey,
    pub member: Pubkey,
    pub proposal: Pubkey,
}
impl From<ProposalActivateAccounts<'_, '_>> for ProposalActivateKeys {
    fn from(accounts: ProposalActivateAccounts) -> Self {
        Self {
            multisig: *accounts.multisig.key,
            member: *accounts.member.key,
            proposal: *accounts.proposal.key,
        }
    }
}
impl From<ProposalActivateKeys> for [AccountMeta; PROPOSAL_ACTIVATE_IX_ACCOUNTS_LEN] {
    fn from(keys: ProposalActivateKeys) -> Self {
        [
            AccountMeta {
                pubkey: keys.multisig,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.member,
                is_signer: true,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.proposal,
                is_signer: false,
                is_writable: true,
            },
        ]
    }
}
impl From<[Pubkey; PROPOSAL_ACTIVATE_IX_ACCOUNTS_LEN]> for ProposalActivateKeys {
    fn from(pubkeys: [Pubkey; PROPOSAL_ACTIVATE_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            multisig: pubkeys[0],
            member: pubkeys[1],
            proposal: pubkeys[2],
        }
    }
}
impl From<&[String]> for ProposalActivateKeys {
    fn from(pubkeys: &[String]) -> Self {
        Self {
            multisig: pubkeys[0].parse().unwrap(),
            member: pubkeys[1].parse().unwrap(),
            proposal: pubkeys[2].parse().unwrap(),
        }
    }
}
impl<'info> From<ProposalActivateAccounts<'_, 'info>>
    for [AccountInfo<'info>; PROPOSAL_ACTIVATE_IX_ACCOUNTS_LEN]
{
    fn from(accounts: ProposalActivateAccounts<'_, 'info>) -> Self {
        [
            accounts.multisig.clone(),
            accounts.member.clone(),
            accounts.proposal.clone(),
        ]
    }
}
impl<'me, 'info> From<&'me [AccountInfo<'info>; PROPOSAL_ACTIVATE_IX_ACCOUNTS_LEN]>
    for ProposalActivateAccounts<'me, 'info>
{
    fn from(arr: &'me [AccountInfo<'info>; PROPOSAL_ACTIVATE_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            multisig: &arr[0],
            member: &arr[1],
            proposal: &arr[2],
        }
    }
}
pub const PROPOSAL_ACTIVATE_IX_DISCM: u8 = 22u8;
#[derive(Clone, Debug, PartialEq)]
pub struct ProposalActivateIxData;
impl ProposalActivateIxData {
    pub fn deserialize(buf: &[u8]) -> std::io::Result<Self> {
        if buf.is_empty() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Instruction data is empty",
            ));
        }
        let maybe_discm = buf[0];
        if maybe_discm != PROPOSAL_ACTIVATE_IX_DISCM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "discm does not match. Expected: {}. Received: {}",
                    PROPOSAL_ACTIVATE_IX_DISCM, maybe_discm
                ),
            ));
        }
        Ok(Self)
    }
    pub fn serialize<W: std::io::Write>(&self, mut writer: W) -> std::io::Result<()> {
        writer.write_all(&[PROPOSAL_ACTIVATE_IX_DISCM])
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        let mut data = Vec::new();
        self.serialize(&mut data)?;
        Ok(data)
    }
}
pub fn proposal_activate_ix_with_program_id(
    program_id: Pubkey,
    keys: ProposalActivateKeys,
) -> std::io::Result<Instruction> {
    let metas: [AccountMeta; PROPOSAL_ACTIVATE_IX_ACCOUNTS_LEN] = keys.into();
    Ok(Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: ProposalActivateIxData.try_to_vec()?,
    })
}
pub fn proposal_activate_ix(keys: ProposalActivateKeys) -> std::io::Result<Instruction> {
    proposal_activate_ix_with_program_id(crate::ID, keys)
}
pub fn proposal_activate_invoke_with_program_id(
    program_id: Pubkey,
    accounts: ProposalActivateAccounts<'_, '_>,
) -> ProgramResult {
    let keys: ProposalActivateKeys = accounts.into();
    let ix = proposal_activate_ix_with_program_id(program_id, keys)?;
    invoke_instruction(&ix, accounts)
}
pub fn proposal_activate_invoke(accounts: ProposalActivateAccounts<'_, '_>) -> ProgramResult {
    proposal_activate_invoke_with_program_id(crate::ID, accounts)
}
pub fn proposal_activate_invoke_signed_with_program_id(
    program_id: Pubkey,
    accounts: ProposalActivateAccounts<'_, '_>,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    let keys: ProposalActivateKeys = accounts.into();
    let ix = proposal_activate_ix_with_program_id(program_id, keys)?;
    invoke_instruction_signed(&ix, accounts, seeds)
}
pub fn proposal_activate_invoke_signed(
    accounts: ProposalActivateAccounts<'_, '_>,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    proposal_activate_invoke_signed_with_program_id(crate::ID, accounts, seeds)
}
pub fn proposal_activate_verify_account_keys(
    accounts: ProposalActivateAccounts<'_, '_>,
    keys: ProposalActivateKeys,
) -> Result<(), (Pubkey, Pubkey)> {
    for (actual, expected) in [
        (*accounts.multisig.key, keys.multisig),
        (*accounts.member.key, keys.member),
        (*accounts.proposal.key, keys.proposal),
    ] {
        if actual != expected {
            return Err((actual, expected));
        }
    }
    Ok(())
}
