//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//! Anchor accounts module
//! Generated account definitions with 8-byte discriminator support
//! Each account is defined in its own file
pub mod batch;
pub mod config_transaction;
pub mod multisig;
pub mod program_config;
pub mod proposal;
pub mod spending_limit;
pub mod vault_batch_transaction;
pub mod vault_transaction;
pub use batch::*;
pub use config_transaction::*;
pub use multisig::*;
pub use program_config::*;
pub use proposal::*;
pub use spending_limit::*;
pub use vault_batch_transaction::*;
pub use vault_transaction::*;
