//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!Event: CompositionFee
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const COMPOSITION_FEE_EVENT_DISCM: [u8; 8] =
    [128u8, 151u8, 123u8, 106u8, 17u8, 102u8, 113u8, 142u8];
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CompositionFee {
    pub discriminator: [u8; 8],
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub from: Pubkey,
    pub bin_id: i16,
    pub token_x_fee_amount: u64,
    pub token_y_fee_amount: u64,
    pub protocol_token_x_fee_amount: u64,
    pub protocol_token_y_fee_amount: u64,
}
impl Default for CompositionFee {
    fn default() -> Self {
        Self {
            discriminator: COMPOSITION_FEE_EVENT_DISCM,
            from: Default::default(),
            bin_id: Default::default(),
            token_x_fee_amount: Default::default(),
            token_y_fee_amount: Default::default(),
            protocol_token_x_fee_amount: Default::default(),
            protocol_token_y_fee_amount: Default::default(),
        }
    }
}
impl CompositionFee {
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
        borsh::BorshDeserialize::deserialize(&mut &data[..])
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e.to_string()))
    }
}
