//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use crate::OrderType;
use crate::Side;
use borsh::{BorshDeserialize, BorshSerialize};
#[derive(Clone, Debug, BorshDeserialize, BorshSerialize, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct NewOrderInstructionV1 {
    pub side: Side,
    pub limit_price: u64,
    pub max_qty: u64,
    pub order_type: OrderType,
    pub client_id: u64,
}
impl Default for NewOrderInstructionV1 {
    fn default() -> Self {
        Self {
            side: Default::default(),
            limit_price: Default::default(),
            max_qty: Default::default(),
            order_type: Default::default(),
            client_id: Default::default(),
        }
    }
}
