//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!DynamicFeeConfig
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DynamicFeeConfig {
    pub initialized: u8,
    pub padding: [u8; 7],
    pub max_volatility_accumulator: u32,
    pub variable_fee_control: u32,
    pub bin_step: u16,
    pub filter_period: u16,
    pub decay_period: u16,
    pub reduction_factor: u16,
    #[cfg_attr(feature = "serde", serde(rename = "padding2"))]
    pub padding_2: [u8; 8],
    #[cfg_attr(feature = "serde", serde(rename = "bin_step_u128"))]
    pub bin_step_u_128: u128,
}
impl Default for DynamicFeeConfig {
    fn default() -> Self {
        Self {
            initialized: Default::default(),
            padding: Default::default(),
            max_volatility_accumulator: Default::default(),
            variable_fee_control: Default::default(),
            bin_step: Default::default(),
            filter_period: Default::default(),
            decay_period: Default::default(),
            reduction_factor: Default::default(),
            padding_2: Default::default(),
            bin_step_u_128: Default::default(),
        }
    }
}
impl DynamicFeeConfig {
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
        borsh::from_slice(data)
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e.to_string()))
    }
}
