//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!Instruction: batchAddTransaction
///Add a transaction to the batch.
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const BATCH_ADD_TRANSACTION_IX_DISCM: [u8; 8] = [59u8, 60u8, 91u8, 9u8, 38u8, 3u8, 60u8, 172u8];
pub const BATCH_ADD_TRANSACTION_IX_ACCOUNTS_LEN: usize = 7;
///Add a transaction to the batch.
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BatchAddTransactionIxData {
    pub discriminator: [u8; 8],
    pub args: crate::types::BatchAddTransactionArgs,
}
impl Default for BatchAddTransactionIxData {
    fn default() -> Self {
        Self {
            discriminator: BATCH_ADD_TRANSACTION_IX_DISCM,
            args: Default::default(),
        }
    }
}
impl BatchAddTransactionIxData {
    pub fn new(args: crate::types::BatchAddTransactionArgs) -> Self {
        Self {
            discriminator: Self::discriminator(),
            args,
        }
    }
    pub fn from_bytes(buf: &[u8]) -> std::io::Result<Self> {
        borsh::BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn discriminator() -> [u8; 8] {
        BATCH_ADD_TRANSACTION_IX_DISCM
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!(
                    "\"discriminator\":[{}]",
                    self.discriminator
                        .iter()
                        .map(|x| x.to_string())
                        .collect::<Vec<_>>()
                        .join(",")
                ),
                format!(
                    "\"{}\":{}",
                    "args",
                    serde_json::to_string(&self.args).unwrap_or_else(|_| "null".to_string())
                )
            ]
            .join(",")
        )
    }
}
#[derive(Copy, Clone, Debug, PartialEq, Default)]
pub struct BatchAddTransactionKeys {
    pub multisig: Pubkey,
    pub proposal: Pubkey,
    pub batch: Pubkey,
    pub transaction: Pubkey,
    pub member: Pubkey,
    pub rent_payer: Pubkey,
    pub system_program: Pubkey,
}
impl From<&[Pubkey]> for BatchAddTransactionKeys {
    fn from(pubkeys: &[Pubkey]) -> Self {
        Self {
            multisig: pubkeys[0],
            proposal: pubkeys[1],
            batch: pubkeys[2],
            transaction: pubkeys[3],
            member: pubkeys[4],
            rent_payer: pubkeys[5],
            system_program: pubkeys[6],
        }
    }
}
impl BatchAddTransactionKeys {
    /// Convert Keys to Vec<Pubkey>
    pub fn to_vec(&self) -> Vec<Pubkey> {
        vec![
            self.multisig,
            self.proposal,
            self.batch,
            self.transaction,
            self.member,
            self.rent_payer,
            self.system_program,
        ]
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!("\"{}\":\"{}\"", "multisig", self.multisig),
                format!("\"{}\":\"{}\"", "proposal", self.proposal),
                format!("\"{}\":\"{}\"", "batch", self.batch),
                format!("\"{}\":\"{}\"", "transaction", self.transaction),
                format!("\"{}\":\"{}\"", "member", self.member),
                format!("\"{}\":\"{}\"", "rentPayer", self.rent_payer),
                format!("\"{}\":\"{}\"", "systemProgram", self.system_program)
            ]
            .join(",")
        )
    }
}
impl From<BatchAddTransactionKeys>
    for [solana_instruction::AccountMeta; BATCH_ADD_TRANSACTION_IX_ACCOUNTS_LEN]
{
    fn from(keys: BatchAddTransactionKeys) -> Self {
        [
            solana_instruction::AccountMeta::new(keys.multisig, false),
            solana_instruction::AccountMeta::new(keys.proposal, false),
            solana_instruction::AccountMeta::new(keys.batch, false),
            solana_instruction::AccountMeta::new(keys.transaction, false),
            solana_instruction::AccountMeta::new(keys.member, false),
            solana_instruction::AccountMeta::new(keys.rent_payer, false),
            solana_instruction::AccountMeta::new(keys.system_program, false),
        ]
    }
}
pub fn batch_add_transaction_ix_with_program_id(
    program_id: Pubkey,
    keys: BatchAddTransactionKeys,
    args: BatchAddTransactionIxData,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    let metas: [solana_instruction::AccountMeta; BATCH_ADD_TRANSACTION_IX_ACCOUNTS_LEN] =
        keys.into();
    Ok(solana_instruction::Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: args.try_to_vec()?,
    })
}
pub fn batch_add_transaction_ix(
    keys: BatchAddTransactionKeys,
    args: BatchAddTransactionIxData,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    batch_add_transaction_ix_with_program_id(crate::ID, keys, args)
}
