//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use super::*;
pub const EVICT_SEAT_IX_ACCOUNTS_LEN: usize = 11;
///Accounts struct for the EvictSeat instruction
#[derive(Copy, Clone, Debug)]
pub struct EvictSeatAccounts<'me, 'info> {
    pub phoenix_program: &'me AccountInfo<'info>,
    pub log_authority: &'me AccountInfo<'info>,
    pub market: &'me AccountInfo<'info>,
    pub market_authority: &'me AccountInfo<'info>,
    pub trader: &'me AccountInfo<'info>,
    pub seat: &'me AccountInfo<'info>,
    pub base_account: &'me AccountInfo<'info>,
    pub quote_account: &'me AccountInfo<'info>,
    pub base_vault: &'me AccountInfo<'info>,
    pub quote_vault: &'me AccountInfo<'info>,
    pub token_program: &'me AccountInfo<'info>,
}
///Public keys struct for the EvictSeat instruction
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct EvictSeatKeys {
    pub phoenix_program: Pubkey,
    pub log_authority: Pubkey,
    pub market: Pubkey,
    pub market_authority: Pubkey,
    pub trader: Pubkey,
    pub seat: Pubkey,
    pub base_account: Pubkey,
    pub quote_account: Pubkey,
    pub base_vault: Pubkey,
    pub quote_vault: Pubkey,
    pub token_program: Pubkey,
}
impl From<EvictSeatAccounts<'_, '_>> for EvictSeatKeys {
    fn from(accounts: EvictSeatAccounts) -> Self {
        Self {
            phoenix_program: *accounts.phoenix_program.key,
            log_authority: *accounts.log_authority.key,
            market: *accounts.market.key,
            market_authority: *accounts.market_authority.key,
            trader: *accounts.trader.key,
            seat: *accounts.seat.key,
            base_account: *accounts.base_account.key,
            quote_account: *accounts.quote_account.key,
            base_vault: *accounts.base_vault.key,
            quote_vault: *accounts.quote_vault.key,
            token_program: *accounts.token_program.key,
        }
    }
}
impl From<EvictSeatKeys> for [AccountMeta; EVICT_SEAT_IX_ACCOUNTS_LEN] {
    fn from(keys: EvictSeatKeys) -> Self {
        [
            AccountMeta {
                pubkey: keys.phoenix_program,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.log_authority,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.market,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.market_authority,
                is_signer: true,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.trader,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.seat,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.base_account,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.quote_account,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.base_vault,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.quote_vault,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.token_program,
                is_signer: false,
                is_writable: false,
            },
        ]
    }
}
impl From<[Pubkey; EVICT_SEAT_IX_ACCOUNTS_LEN]> for EvictSeatKeys {
    fn from(pubkeys: [Pubkey; EVICT_SEAT_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            phoenix_program: pubkeys[0],
            log_authority: pubkeys[1],
            market: pubkeys[2],
            market_authority: pubkeys[3],
            trader: pubkeys[4],
            seat: pubkeys[5],
            base_account: pubkeys[6],
            quote_account: pubkeys[7],
            base_vault: pubkeys[8],
            quote_vault: pubkeys[9],
            token_program: pubkeys[10],
        }
    }
}
impl From<&[String]> for EvictSeatKeys {
    fn from(pubkeys: &[String]) -> Self {
        Self {
            phoenix_program: pubkeys[0].parse().unwrap(),
            log_authority: pubkeys[1].parse().unwrap(),
            market: pubkeys[2].parse().unwrap(),
            market_authority: pubkeys[3].parse().unwrap(),
            trader: pubkeys[4].parse().unwrap(),
            seat: pubkeys[5].parse().unwrap(),
            base_account: pubkeys[6].parse().unwrap(),
            quote_account: pubkeys[7].parse().unwrap(),
            base_vault: pubkeys[8].parse().unwrap(),
            quote_vault: pubkeys[9].parse().unwrap(),
            token_program: pubkeys[10].parse().unwrap(),
        }
    }
}
impl<'info> From<EvictSeatAccounts<'_, 'info>>
    for [AccountInfo<'info>; EVICT_SEAT_IX_ACCOUNTS_LEN]
{
    fn from(accounts: EvictSeatAccounts<'_, 'info>) -> Self {
        [
            accounts.phoenix_program.clone(),
            accounts.log_authority.clone(),
            accounts.market.clone(),
            accounts.market_authority.clone(),
            accounts.trader.clone(),
            accounts.seat.clone(),
            accounts.base_account.clone(),
            accounts.quote_account.clone(),
            accounts.base_vault.clone(),
            accounts.quote_vault.clone(),
            accounts.token_program.clone(),
        ]
    }
}
impl<'me, 'info> From<&'me [AccountInfo<'info>; EVICT_SEAT_IX_ACCOUNTS_LEN]>
    for EvictSeatAccounts<'me, 'info>
{
    fn from(arr: &'me [AccountInfo<'info>; EVICT_SEAT_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            phoenix_program: &arr[0],
            log_authority: &arr[1],
            market: &arr[2],
            market_authority: &arr[3],
            trader: &arr[4],
            seat: &arr[5],
            base_account: &arr[6],
            quote_account: &arr[7],
            base_vault: &arr[8],
            quote_vault: &arr[9],
            token_program: &arr[10],
        }
    }
}
pub const EVICT_SEAT_IX_DISCM: u8 = 24u8;
#[derive(Clone, Debug, PartialEq)]
pub struct EvictSeatIxData;
impl EvictSeatIxData {
    pub fn deserialize(buf: &[u8]) -> std::io::Result<Self> {
        if buf.is_empty() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Instruction data is empty",
            ));
        }
        let maybe_discm = buf[0];
        if maybe_discm != EVICT_SEAT_IX_DISCM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "discm does not match. Expected: {}. Received: {}",
                    EVICT_SEAT_IX_DISCM, maybe_discm
                ),
            ));
        }
        Ok(Self)
    }
    pub fn serialize<W: std::io::Write>(&self, mut writer: W) -> std::io::Result<()> {
        writer.write_all(&[EVICT_SEAT_IX_DISCM])
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        let mut data = Vec::new();
        self.serialize(&mut data)?;
        Ok(data)
    }
}
pub fn evict_seat_ix_with_program_id(
    program_id: Pubkey,
    keys: EvictSeatKeys,
) -> std::io::Result<Instruction> {
    let metas: [AccountMeta; EVICT_SEAT_IX_ACCOUNTS_LEN] = keys.into();
    Ok(Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: EvictSeatIxData.try_to_vec()?,
    })
}
pub fn evict_seat_ix(keys: EvictSeatKeys) -> std::io::Result<Instruction> {
    evict_seat_ix_with_program_id(crate::ID, keys)
}
pub fn evict_seat_invoke_with_program_id(
    program_id: Pubkey,
    accounts: EvictSeatAccounts<'_, '_>,
) -> ProgramResult {
    let keys: EvictSeatKeys = accounts.into();
    let ix = evict_seat_ix_with_program_id(program_id, keys)?;
    invoke_instruction(&ix, accounts)
}
pub fn evict_seat_invoke(accounts: EvictSeatAccounts<'_, '_>) -> ProgramResult {
    evict_seat_invoke_with_program_id(crate::ID, accounts)
}
pub fn evict_seat_invoke_signed_with_program_id(
    program_id: Pubkey,
    accounts: EvictSeatAccounts<'_, '_>,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    let keys: EvictSeatKeys = accounts.into();
    let ix = evict_seat_ix_with_program_id(program_id, keys)?;
    invoke_instruction_signed(&ix, accounts, seeds)
}
pub fn evict_seat_invoke_signed(
    accounts: EvictSeatAccounts<'_, '_>,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    evict_seat_invoke_signed_with_program_id(crate::ID, accounts, seeds)
}
pub fn evict_seat_verify_account_keys(
    accounts: EvictSeatAccounts<'_, '_>,
    keys: EvictSeatKeys,
) -> Result<(), (Pubkey, Pubkey)> {
    for (actual, expected) in [
        (*accounts.phoenix_program.key, keys.phoenix_program),
        (*accounts.log_authority.key, keys.log_authority),
        (*accounts.market.key, keys.market),
        (*accounts.market_authority.key, keys.market_authority),
        (*accounts.trader.key, keys.trader),
        (*accounts.seat.key, keys.seat),
        (*accounts.base_account.key, keys.base_account),
        (*accounts.quote_account.key, keys.quote_account),
        (*accounts.base_vault.key, keys.base_vault),
        (*accounts.quote_vault.key, keys.quote_vault),
        (*accounts.token_program.key, keys.token_program),
    ] {
        if actual != expected {
            return Err((actual, expected));
        }
    }
    Ok(())
}
