//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

use super::*;
pub const PLACE_MULTIPLE_POST_ONLY_ORDERS_IX_ACCOUNTS_LEN: usize = 10;
///Accounts struct for the PlaceMultiplePostOnlyOrders instruction
#[derive(Copy, Clone, Debug)]
pub struct PlaceMultiplePostOnlyOrdersAccounts<'me, 'info> {
    pub phoenix_program: &'me AccountInfo<'info>,
    pub log_authority: &'me AccountInfo<'info>,
    pub market: &'me AccountInfo<'info>,
    pub trader: &'me AccountInfo<'info>,
    pub seat: &'me AccountInfo<'info>,
    pub base_account: &'me AccountInfo<'info>,
    pub quote_account: &'me AccountInfo<'info>,
    pub base_vault: &'me AccountInfo<'info>,
    pub quote_vault: &'me AccountInfo<'info>,
    pub token_program: &'me AccountInfo<'info>,
}
///Public keys struct for the PlaceMultiplePostOnlyOrders instruction
#[derive(Copy, Clone, Debug, PartialEq)]
pub struct PlaceMultiplePostOnlyOrdersKeys {
    pub phoenix_program: Pubkey,
    pub log_authority: Pubkey,
    pub market: Pubkey,
    pub trader: Pubkey,
    pub seat: Pubkey,
    pub base_account: Pubkey,
    pub quote_account: Pubkey,
    pub base_vault: Pubkey,
    pub quote_vault: Pubkey,
    pub token_program: Pubkey,
}
impl From<PlaceMultiplePostOnlyOrdersAccounts<'_, '_>> for PlaceMultiplePostOnlyOrdersKeys {
    fn from(accounts: PlaceMultiplePostOnlyOrdersAccounts) -> Self {
        Self {
            phoenix_program: *accounts.phoenix_program.key,
            log_authority: *accounts.log_authority.key,
            market: *accounts.market.key,
            trader: *accounts.trader.key,
            seat: *accounts.seat.key,
            base_account: *accounts.base_account.key,
            quote_account: *accounts.quote_account.key,
            base_vault: *accounts.base_vault.key,
            quote_vault: *accounts.quote_vault.key,
            token_program: *accounts.token_program.key,
        }
    }
}
impl From<PlaceMultiplePostOnlyOrdersKeys>
    for [AccountMeta; PLACE_MULTIPLE_POST_ONLY_ORDERS_IX_ACCOUNTS_LEN]
{
    fn from(keys: PlaceMultiplePostOnlyOrdersKeys) -> Self {
        [
            AccountMeta {
                pubkey: keys.phoenix_program,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.log_authority,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.market,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.trader,
                is_signer: true,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.seat,
                is_signer: false,
                is_writable: false,
            },
            AccountMeta {
                pubkey: keys.base_account,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.quote_account,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.base_vault,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.quote_vault,
                is_signer: false,
                is_writable: true,
            },
            AccountMeta {
                pubkey: keys.token_program,
                is_signer: false,
                is_writable: false,
            },
        ]
    }
}
impl From<[Pubkey; PLACE_MULTIPLE_POST_ONLY_ORDERS_IX_ACCOUNTS_LEN]>
    for PlaceMultiplePostOnlyOrdersKeys
{
    fn from(pubkeys: [Pubkey; PLACE_MULTIPLE_POST_ONLY_ORDERS_IX_ACCOUNTS_LEN]) -> Self {
        Self {
            phoenix_program: pubkeys[0],
            log_authority: pubkeys[1],
            market: pubkeys[2],
            trader: pubkeys[3],
            seat: pubkeys[4],
            base_account: pubkeys[5],
            quote_account: pubkeys[6],
            base_vault: pubkeys[7],
            quote_vault: pubkeys[8],
            token_program: pubkeys[9],
        }
    }
}
impl From<&[String]> for PlaceMultiplePostOnlyOrdersKeys {
    fn from(pubkeys: &[String]) -> Self {
        Self {
            phoenix_program: pubkeys[0].parse().unwrap(),
            log_authority: pubkeys[1].parse().unwrap(),
            market: pubkeys[2].parse().unwrap(),
            trader: pubkeys[3].parse().unwrap(),
            seat: pubkeys[4].parse().unwrap(),
            base_account: pubkeys[5].parse().unwrap(),
            quote_account: pubkeys[6].parse().unwrap(),
            base_vault: pubkeys[7].parse().unwrap(),
            quote_vault: pubkeys[8].parse().unwrap(),
            token_program: pubkeys[9].parse().unwrap(),
        }
    }
}
impl<'info> From<PlaceMultiplePostOnlyOrdersAccounts<'_, 'info>>
    for [AccountInfo<'info>; PLACE_MULTIPLE_POST_ONLY_ORDERS_IX_ACCOUNTS_LEN]
{
    fn from(accounts: PlaceMultiplePostOnlyOrdersAccounts<'_, 'info>) -> Self {
        [
            accounts.phoenix_program.clone(),
            accounts.log_authority.clone(),
            accounts.market.clone(),
            accounts.trader.clone(),
            accounts.seat.clone(),
            accounts.base_account.clone(),
            accounts.quote_account.clone(),
            accounts.base_vault.clone(),
            accounts.quote_vault.clone(),
            accounts.token_program.clone(),
        ]
    }
}
impl<'me, 'info> From<&'me [AccountInfo<'info>; PLACE_MULTIPLE_POST_ONLY_ORDERS_IX_ACCOUNTS_LEN]>
    for PlaceMultiplePostOnlyOrdersAccounts<'me, 'info>
{
    fn from(
        arr: &'me [AccountInfo<'info>; PLACE_MULTIPLE_POST_ONLY_ORDERS_IX_ACCOUNTS_LEN],
    ) -> Self {
        Self {
            phoenix_program: &arr[0],
            log_authority: &arr[1],
            market: &arr[2],
            trader: &arr[3],
            seat: &arr[4],
            base_account: &arr[5],
            quote_account: &arr[6],
            base_vault: &arr[7],
            quote_vault: &arr[8],
            token_program: &arr[9],
        }
    }
}
pub const PLACE_MULTIPLE_POST_ONLY_ORDERS_IX_DISCM: u8 = 16u8;
///Arguments for the PlaceMultiplePostOnlyOrders instruction
#[derive(BorshDeserialize, BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PlaceMultiplePostOnlyOrdersIxArgs {
    pub discriminator: u8,
    pub multiple_order_packet: MultipleOrderPacket,
}
impl Default for PlaceMultiplePostOnlyOrdersIxArgs {
    fn default() -> Self {
        Self {
            discriminator: 16u8,
            multiple_order_packet: Default::default(),
        }
    }
}
#[derive(Clone, Debug, PartialEq)]
pub struct PlaceMultiplePostOnlyOrdersIxData(pub PlaceMultiplePostOnlyOrdersIxArgs);
impl From<PlaceMultiplePostOnlyOrdersIxArgs> for PlaceMultiplePostOnlyOrdersIxData {
    fn from(args: PlaceMultiplePostOnlyOrdersIxArgs) -> Self {
        Self(args)
    }
}
impl PlaceMultiplePostOnlyOrdersIxData {
    pub fn deserialize(buf: &[u8]) -> std::io::Result<Self> {
        if buf.is_empty() {
            return Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Instruction data is empty",
            ));
        }
        let maybe_discm = buf[0];
        if maybe_discm != PLACE_MULTIPLE_POST_ONLY_ORDERS_IX_DISCM {
            return Err(std::io::Error::new(
                std::io::ErrorKind::Other,
                format!(
                    "discm does not match. Expected: {}. Received: {}",
                    PLACE_MULTIPLE_POST_ONLY_ORDERS_IX_DISCM, maybe_discm
                ),
            ));
        }
        let mut reader = &buf[1..];
        Ok(Self(PlaceMultiplePostOnlyOrdersIxArgs::deserialize(
            &mut reader,
        )?))
    }
    pub fn serialize<W: std::io::Write>(&self, mut writer: W) -> std::io::Result<()> {
        writer.write_all(&[PLACE_MULTIPLE_POST_ONLY_ORDERS_IX_DISCM])?;
        self.0.serialize(&mut writer)
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        let mut data = Vec::new();
        self.serialize(&mut data)?;
        Ok(data)
    }
}
pub fn place_multiple_post_only_orders_ix_with_program_id(
    program_id: Pubkey,
    keys: PlaceMultiplePostOnlyOrdersKeys,
    args: PlaceMultiplePostOnlyOrdersIxArgs,
) -> std::io::Result<Instruction> {
    let metas: [AccountMeta; PLACE_MULTIPLE_POST_ONLY_ORDERS_IX_ACCOUNTS_LEN] = keys.into();
    let data: PlaceMultiplePostOnlyOrdersIxData = args.into();
    Ok(Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: data.try_to_vec()?,
    })
}
pub fn place_multiple_post_only_orders_ix(
    keys: PlaceMultiplePostOnlyOrdersKeys,
    args: PlaceMultiplePostOnlyOrdersIxArgs,
) -> std::io::Result<Instruction> {
    place_multiple_post_only_orders_ix_with_program_id(crate::ID, keys, args)
}
pub fn place_multiple_post_only_orders_invoke_with_program_id(
    program_id: Pubkey,
    accounts: PlaceMultiplePostOnlyOrdersAccounts<'_, '_>,
    args: PlaceMultiplePostOnlyOrdersIxArgs,
) -> ProgramResult {
    let keys: PlaceMultiplePostOnlyOrdersKeys = accounts.into();
    let ix = place_multiple_post_only_orders_ix_with_program_id(program_id, keys, args)?;
    invoke_instruction(&ix, accounts)
}
pub fn place_multiple_post_only_orders_invoke(
    accounts: PlaceMultiplePostOnlyOrdersAccounts<'_, '_>,
    args: PlaceMultiplePostOnlyOrdersIxArgs,
) -> ProgramResult {
    place_multiple_post_only_orders_invoke_with_program_id(crate::ID, accounts, args)
}
pub fn place_multiple_post_only_orders_invoke_signed_with_program_id(
    program_id: Pubkey,
    accounts: PlaceMultiplePostOnlyOrdersAccounts<'_, '_>,
    args: PlaceMultiplePostOnlyOrdersIxArgs,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    let keys: PlaceMultiplePostOnlyOrdersKeys = accounts.into();
    let ix = place_multiple_post_only_orders_ix_with_program_id(program_id, keys, args)?;
    invoke_instruction_signed(&ix, accounts, seeds)
}
pub fn place_multiple_post_only_orders_invoke_signed(
    accounts: PlaceMultiplePostOnlyOrdersAccounts<'_, '_>,
    args: PlaceMultiplePostOnlyOrdersIxArgs,
    seeds: &[&[&[u8]]],
) -> ProgramResult {
    place_multiple_post_only_orders_invoke_signed_with_program_id(crate::ID, accounts, args, seeds)
}
pub fn place_multiple_post_only_orders_verify_account_keys(
    accounts: PlaceMultiplePostOnlyOrdersAccounts<'_, '_>,
    keys: PlaceMultiplePostOnlyOrdersKeys,
) -> Result<(), (Pubkey, Pubkey)> {
    for (actual, expected) in [
        (*accounts.phoenix_program.key, keys.phoenix_program),
        (*accounts.log_authority.key, keys.log_authority),
        (*accounts.market.key, keys.market),
        (*accounts.trader.key, keys.trader),
        (*accounts.seat.key, keys.seat),
        (*accounts.base_account.key, keys.base_account),
        (*accounts.quote_account.key, keys.quote_account),
        (*accounts.base_vault.key, keys.base_vault),
        (*accounts.quote_vault.key, keys.quote_vault),
        (*accounts.token_program.key, keys.token_program),
    ] {
        if actual != expected {
            return Err((actual, expected));
        }
    }
    Ok(())
}
impl PlaceMultiplePostOnlyOrdersIxArgs {
    pub fn serialize<W: std::io::Write>(&self, mut writer: W) -> std::io::Result<()> {
        BorshSerialize::serialize(self, &mut writer)
    }
    pub fn deserialize(buf: &[u8]) -> std::io::Result<Self> {
        BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
}
impl From<PlaceMultiplePostOnlyOrdersIxArgs> for PhoenixProgramIx {
    fn from(args: PlaceMultiplePostOnlyOrdersIxArgs) -> Self {
        Self::PlaceMultiplePostOnlyOrders(args)
    }
}
