//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!Event: EvtCreateDammV2MigrationMetadata
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const EVT_CREATE_DAMM_V2_MIGRATION_METADATA_EVENT_DISCM: [u8; 8] =
    [103u8, 111u8, 132u8, 168u8, 140u8, 253u8, 150u8, 114u8];
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct EvtCreateDammV2MigrationMetadata {
    pub discriminator: [u8; 8],
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub virtual_pool: Pubkey,
}
impl Default for EvtCreateDammV2MigrationMetadata {
    fn default() -> Self {
        Self {
            discriminator: EVT_CREATE_DAMM_V2_MIGRATION_METADATA_EVENT_DISCM,
            virtual_pool: Default::default(),
        }
    }
}
impl EvtCreateDammV2MigrationMetadata {
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
        borsh::BorshDeserialize::deserialize(&mut &data[..])
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e.to_string()))
    }
}
