//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!Event: EvtClaimCreatorTradingFee
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const EVT_CLAIM_CREATOR_TRADING_FEE_EVENT_DISCM: [u8; 8] =
    [154u8, 228u8, 215u8, 202u8, 133u8, 155u8, 214u8, 138u8];
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct EvtClaimCreatorTradingFee {
    pub discriminator: [u8; 8],
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub pool: Pubkey,
    pub token_base_amount: u64,
    pub token_quote_amount: u64,
}
impl Default for EvtClaimCreatorTradingFee {
    fn default() -> Self {
        Self {
            discriminator: EVT_CLAIM_CREATOR_TRADING_FEE_EVENT_DISCM,
            pool: Default::default(),
            token_base_amount: Default::default(),
            token_quote_amount: Default::default(),
        }
    }
}
impl EvtClaimCreatorTradingFee {
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
        borsh::BorshDeserialize::deserialize(&mut &data[..])
            .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e.to_string()))
    }
}
