//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const BONDING_CURVE_ACCOUNT_DISCM: [u8; 8] =
    [23u8, 183u8, 248u8, 55u8, 96u8, 216u8, 172u8, 96u8];
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BondingCurve {
    pub discriminator: [u8; 8],
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub creator: Pubkey,
    #[cfg_attr(
        feature = "serde",
        serde(with = "serde_with::As::<serde_with::DisplayFromStr>")
    )]
    pub mint: Pubkey,
    pub virtual_sol_reserves: u64,
    ///virtual token reserves is deprecated, we now use the xyk formula instead
    ///and it only requires virtual sol reserves
    ///to maintain backwards compatibility, if damping term is 30, we use the old formula
    ///and we still need virtual_token_reserves to be set correctly
    pub virtual_token_reserves: u64,
    pub graduation_target: u64,
    pub graduation_fee: u64,
    pub sol_reserves: u64,
    pub token_reserves: u64,
    ///In reality, this is now more like a bonding_curve_selector
    pub damping_term: u8,
    pub swap_fee_basis_points: u8,
    pub token_for_stakers_basis_points: u16,
    pub status: crate::types::BondingCurveStatus,
}
impl Default for BondingCurve {
    fn default() -> Self {
        Self {
            discriminator: BONDING_CURVE_ACCOUNT_DISCM,
            creator: Default::default(),
            mint: Default::default(),
            virtual_sol_reserves: Default::default(),
            virtual_token_reserves: Default::default(),
            graduation_target: Default::default(),
            graduation_fee: Default::default(),
            sol_reserves: Default::default(),
            token_reserves: Default::default(),
            damping_term: Default::default(),
            swap_fee_basis_points: Default::default(),
            token_for_stakers_basis_points: Default::default(),
            status: Default::default(),
        }
    }
}
impl BondingCurve {
    pub const MEM_LEN: usize = std::mem::size_of::<Self>();
    pub const PACKED_LEN: usize = 132usize;
    pub fn discriminator() -> [u8; 8] {
        BONDING_CURVE_ACCOUNT_DISCM
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    pub fn from_bytes(data: &[u8]) -> Result<Self, crate::parsers::accounts::AccountParseError> {
        if data.len() < 8 {
            return Err(crate::parsers::accounts::AccountParseError::DataTooShort {
                expected: 8,
                found: data.len(),
            });
        }
        let expected_discriminator = Self::discriminator();
        if &data[0..8] != expected_discriminator {
            let mut found = [0u8; 8];
            found.copy_from_slice(&data[0..8]);
            return Err(
                crate::parsers::accounts::AccountParseError::DiscriminatorMismatch {
                    expected: expected_discriminator,
                    found,
                },
            );
        }
        if data.len() != Self::PACKED_LEN {
            return Err(
                crate::parsers::accounts::AccountParseError::IncorrectLength {
                    expected: Self::PACKED_LEN,
                    found: data.len(),
                },
            );
        }
        borsh::BorshDeserialize::deserialize(&mut &data[..]).map_err(|e| {
            crate::parsers::accounts::AccountParseError::DeserializationFailed(e.to_string())
        })
    }
}
