//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-06
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//! Program constants
pub const BASIS_POINT_MAX: i32 = 10000i32;
pub const MAX_BIN_PER_ARRAY: usize = 70usize;
pub const MAX_BIN_PER_POSITION: usize = 70usize;
pub const MIN_BIN_ID: i32 = 0i32;
pub const MAX_BIN_ID: i32 = 443636i32;
pub const MAX_FEE_RATE: u64 = 0u64;
pub const FEE_PRECISION: u64 = 0u64;
pub const NUM_REWARDS: usize = 2usize;
pub const MIN_REWARD_DURATION: u64 = 1u64;
pub const MAX_REWARD_DURATION: u64 = 31536000u64;
pub const EXTENSION_BINARRAY_BITMAP_SIZE: usize = 12usize;
pub const BIN_ARRAY_BITMAP_SIZE: i32 = 512i32;
pub const MAX_REWARD_BIN_SPLIT: usize = 15usize;
