//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!Instruction: claim_reward2
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const CLAIM_REWARD_2_IX_DISCM: [u8; 8] = [190u8, 3u8, 127u8, 119u8, 178u8, 87u8, 157u8, 183u8];
pub const CLAIM_REWARD_2_IX_ACCOUNTS_LEN: usize = 10;
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClaimReward2IxData {
    pub discriminator: [u8; 8],
    pub reward_index: u64,
    pub min_bin_id: i32,
    pub max_bin_id: i32,
    pub remaining_accounts_info: crate::types::RemainingAccountsInfo,
}
impl Default for ClaimReward2IxData {
    fn default() -> Self {
        Self {
            discriminator: CLAIM_REWARD_2_IX_DISCM,
            reward_index: Default::default(),
            min_bin_id: Default::default(),
            max_bin_id: Default::default(),
            remaining_accounts_info: Default::default(),
        }
    }
}
impl ClaimReward2IxData {
    pub fn new(
        reward_index: u64,
        min_bin_id: i32,
        max_bin_id: i32,
        remaining_accounts_info: crate::types::RemainingAccountsInfo,
    ) -> Self {
        Self {
            discriminator: Self::discriminator(),
            reward_index,
            min_bin_id,
            max_bin_id,
            remaining_accounts_info,
        }
    }
    pub fn from_bytes(buf: &[u8]) -> std::io::Result<Self> {
        borsh::BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn discriminator() -> [u8; 8] {
        CLAIM_REWARD_2_IX_DISCM
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!(
                    "\"discriminator\":[{}]",
                    self.discriminator
                        .iter()
                        .map(|x| x.to_string())
                        .collect::<Vec<_>>()
                        .join(",")
                ),
                format!("\"{}\":{}", "reward_index", self.reward_index),
                format!("\"{}\":{}", "min_bin_id", self.min_bin_id),
                format!("\"{}\":{}", "max_bin_id", self.max_bin_id),
                format!(
                    "\"{}\":{}",
                    "remaining_accounts_info",
                    serde_json::to_string(&self.remaining_accounts_info)
                        .unwrap_or_else(|_| "null".to_string())
                )
            ]
            .join(",")
        )
    }
}
#[derive(Copy, Clone, Debug, PartialEq, Default)]
pub struct ClaimReward2Keys {
    pub lb_pair: Pubkey,
    pub position: Pubkey,
    pub sender: Pubkey,
    pub reward_vault: Pubkey,
    pub reward_mint: Pubkey,
    pub user_token_account: Pubkey,
    pub token_program: Pubkey,
    pub memo_program: Pubkey,
    pub event_authority: Pubkey,
    pub program: Pubkey,
}
impl From<&[Pubkey]> for ClaimReward2Keys {
    fn from(pubkeys: &[Pubkey]) -> Self {
        Self {
            lb_pair: pubkeys[0],
            position: pubkeys[1],
            sender: pubkeys[2],
            reward_vault: pubkeys[3],
            reward_mint: pubkeys[4],
            user_token_account: pubkeys[5],
            token_program: pubkeys[6],
            memo_program: pubkeys[7],
            event_authority: pubkeys[8],
            program: pubkeys[9],
        }
    }
}
impl ClaimReward2Keys {
    /// Convert Keys to Vec<Pubkey>
    pub fn to_vec(&self) -> Vec<Pubkey> {
        vec![
            self.lb_pair,
            self.position,
            self.sender,
            self.reward_vault,
            self.reward_mint,
            self.user_token_account,
            self.token_program,
            self.memo_program,
            self.event_authority,
            self.program,
        ]
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!("\"{}\":\"{}\"", "lb_pair", self.lb_pair),
                format!("\"{}\":\"{}\"", "position", self.position),
                format!("\"{}\":\"{}\"", "sender", self.sender),
                format!("\"{}\":\"{}\"", "reward_vault", self.reward_vault),
                format!("\"{}\":\"{}\"", "reward_mint", self.reward_mint),
                format!(
                    "\"{}\":\"{}\"",
                    "user_token_account", self.user_token_account
                ),
                format!("\"{}\":\"{}\"", "token_program", self.token_program),
                format!("\"{}\":\"{}\"", "memo_program", self.memo_program),
                format!("\"{}\":\"{}\"", "event_authority", self.event_authority),
                format!("\"{}\":\"{}\"", "program", self.program)
            ]
            .join(",")
        )
    }
}
impl From<ClaimReward2Keys> for [solana_instruction::AccountMeta; CLAIM_REWARD_2_IX_ACCOUNTS_LEN] {
    fn from(keys: ClaimReward2Keys) -> Self {
        [
            solana_instruction::AccountMeta::new(keys.lb_pair, false),
            solana_instruction::AccountMeta::new(keys.position, false),
            solana_instruction::AccountMeta::new(keys.sender, false),
            solana_instruction::AccountMeta::new(keys.reward_vault, false),
            solana_instruction::AccountMeta::new(keys.reward_mint, false),
            solana_instruction::AccountMeta::new(keys.user_token_account, false),
            solana_instruction::AccountMeta::new(keys.token_program, false),
            solana_instruction::AccountMeta::new(keys.memo_program, false),
            solana_instruction::AccountMeta::new(keys.event_authority, false),
            solana_instruction::AccountMeta::new(keys.program, false),
        ]
    }
}
pub fn claim_reward_2_ix_with_program_id(
    program_id: Pubkey,
    keys: ClaimReward2Keys,
    args: ClaimReward2IxData,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    let metas: [solana_instruction::AccountMeta; CLAIM_REWARD_2_IX_ACCOUNTS_LEN] = keys.into();
    Ok(solana_instruction::Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: args.try_to_vec()?,
    })
}
pub fn claim_reward_2_ix(
    keys: ClaimReward2Keys,
    args: ClaimReward2IxData,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    claim_reward_2_ix_with_program_id(crate::ID, keys, args)
}
