//! This file was automatically generated by Solores
//! Solana IDL to Rust interface generator
//!
//! GitHub: https://github.com/cpkt9762/solores
//!
//! Generated on: 2025-08-16
//!
//! DO NOT EDIT - This file is auto-generated
//! Changes will be lost when regenerating from IDL

//!Instruction: update_reward_duration
#[allow(unused_imports)]
use solana_pubkey::Pubkey;
pub const UPDATE_REWARD_DURATION_IX_DISCM: [u8; 8] =
    [138u8, 174u8, 196u8, 169u8, 213u8, 235u8, 254u8, 107u8];
pub const UPDATE_REWARD_DURATION_IX_ACCOUNTS_LEN: usize = 5;
#[derive(borsh::BorshDeserialize, borsh::BorshSerialize, Clone, Debug, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct UpdateRewardDurationIxData {
    pub discriminator: [u8; 8],
    pub reward_index: u64,
    pub new_duration: u64,
}
impl Default for UpdateRewardDurationIxData {
    fn default() -> Self {
        Self {
            discriminator: UPDATE_REWARD_DURATION_IX_DISCM,
            reward_index: Default::default(),
            new_duration: Default::default(),
        }
    }
}
impl UpdateRewardDurationIxData {
    pub fn new(reward_index: u64, new_duration: u64) -> Self {
        Self {
            discriminator: Self::discriminator(),
            reward_index,
            new_duration,
        }
    }
    pub fn from_bytes(buf: &[u8]) -> std::io::Result<Self> {
        borsh::BorshDeserialize::deserialize(&mut &buf[..])
    }
    pub fn discriminator() -> [u8; 8] {
        UPDATE_REWARD_DURATION_IX_DISCM
    }
    pub fn try_to_vec(&self) -> std::io::Result<Vec<u8>> {
        borsh::to_vec(self)
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!(
                    "\"discriminator\":[{}]",
                    self.discriminator
                        .iter()
                        .map(|x| x.to_string())
                        .collect::<Vec<_>>()
                        .join(",")
                ),
                format!("\"{}\":{}", "reward_index", self.reward_index),
                format!("\"{}\":{}", "new_duration", self.new_duration)
            ]
            .join(",")
        )
    }
}
#[derive(Copy, Clone, Debug, PartialEq, Default)]
pub struct UpdateRewardDurationKeys {
    pub lb_pair: Pubkey,
    pub admin: Pubkey,
    pub bin_array: Pubkey,
    pub event_authority: Pubkey,
    pub program: Pubkey,
}
impl From<&[Pubkey]> for UpdateRewardDurationKeys {
    fn from(pubkeys: &[Pubkey]) -> Self {
        Self {
            lb_pair: pubkeys[0],
            admin: pubkeys[1],
            bin_array: pubkeys[2],
            event_authority: pubkeys[3],
            program: pubkeys[4],
        }
    }
}
impl UpdateRewardDurationKeys {
    /// Convert Keys to Vec<Pubkey>
    pub fn to_vec(&self) -> Vec<Pubkey> {
        vec![
            self.lb_pair,
            self.admin,
            self.bin_array,
            self.event_authority,
            self.program,
        ]
    }
    /// Manual JSON serialization
    #[cfg(feature = "serde")]
    pub fn to_json(&self) -> String {
        format!(
            "{{{}}}",
            [
                format!("\"{}\":\"{}\"", "lb_pair", self.lb_pair),
                format!("\"{}\":\"{}\"", "admin", self.admin),
                format!("\"{}\":\"{}\"", "bin_array", self.bin_array),
                format!("\"{}\":\"{}\"", "event_authority", self.event_authority),
                format!("\"{}\":\"{}\"", "program", self.program)
            ]
            .join(",")
        )
    }
}
impl From<UpdateRewardDurationKeys>
    for [solana_instruction::AccountMeta; UPDATE_REWARD_DURATION_IX_ACCOUNTS_LEN]
{
    fn from(keys: UpdateRewardDurationKeys) -> Self {
        [
            solana_instruction::AccountMeta::new(keys.lb_pair, false),
            solana_instruction::AccountMeta::new(keys.admin, false),
            solana_instruction::AccountMeta::new(keys.bin_array, false),
            solana_instruction::AccountMeta::new(keys.event_authority, false),
            solana_instruction::AccountMeta::new(keys.program, false),
        ]
    }
}
pub fn update_reward_duration_ix_with_program_id(
    program_id: Pubkey,
    keys: UpdateRewardDurationKeys,
    args: UpdateRewardDurationIxData,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    let metas: [solana_instruction::AccountMeta; UPDATE_REWARD_DURATION_IX_ACCOUNTS_LEN] =
        keys.into();
    Ok(solana_instruction::Instruction {
        program_id,
        accounts: Vec::from(metas),
        data: args.try_to_vec()?,
    })
}
pub fn update_reward_duration_ix(
    keys: UpdateRewardDurationKeys,
    args: UpdateRewardDurationIxData,
) -> Result<solana_instruction::Instruction, std::io::Error> {
    update_reward_duration_ix_with_program_id(crate::ID, keys, args)
}
